// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package webhookbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
	"github.com/e6qu/sharecrop/internal/webhook"
)

// Method names namespace each webhook.Store method on the wire.
const (
	methodCreateSubscription = "webhook.CreateSubscription"
	methodListSubscriptions  = "webhook.ListSubscriptions"
	methodRevokeSubscription = "webhook.RevokeSubscription"
	methodListDeliveries     = "webhook.ListDeliveries"
)

type createSubscriptionArgs struct {
	Subscription subscriptionWire `json:"subscription"`
	Secret       string           `json:"secret"`
}

type listSubscriptionsArgs struct {
	Owner ownerWire         `json:"owner"`
	Page  corewire.PageWire `json:"page"`
}

type revokeSubscriptionArgs struct {
	Owner ownerWire `json:"owner"`
	ID    string    `json:"id"`
}

type listDeliveriesArgs struct {
	Owner ownerWire         `json:"owner"`
	ID    string            `json:"id"`
	Page  corewire.PageWire `json:"page"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store webhook.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreateSubscription:
		var decoded createSubscriptionArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("webhook bridge: decode CreateSubscription args: %w", err)
		}
		argSubscription, err := decodeSubscription(decoded.Subscription)
		if err != nil {
			return nil, err
		}
		argSecret, err := decodeSecret(decoded.Secret)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateResult(store.CreateSubscription(ctx, argSubscription, argSecret)))
	case methodListSubscriptions:
		var decoded listSubscriptionsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("webhook bridge: decode ListSubscriptions args: %w", err)
		}
		argOwner, err := decodeOwner(decoded.Owner)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.ListSubscriptions(ctx, argOwner, argPage)))
	case methodRevokeSubscription:
		var decoded revokeSubscriptionArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("webhook bridge: decode RevokeSubscription args: %w", err)
		}
		argOwner, err := decodeOwner(decoded.Owner)
		if err != nil {
			return nil, err
		}
		argID, err := corewire.DecodeWebhookSubscriptionID(decoded.ID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRevokeResult(store.RevokeSubscription(ctx, argOwner, argID)))
	case methodListDeliveries:
		var decoded listDeliveriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("webhook bridge: decode ListDeliveries args: %w", err)
		}
		argOwner, err := decodeOwner(decoded.Owner)
		if err != nil {
			return nil, err
		}
		argID, err := corewire.DecodeWebhookSubscriptionID(decoded.ID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeDeliveriesResult(store.ListDeliveries(ctx, argOwner, argID, argPage)))
	default:
		return nil, fmt.Errorf("webhook bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements webhook.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) CreateSubscription(ctx context.Context, argSubscription webhook.Subscription, argSecret webhook.Secret) webhook.CreateStoreResult {
	args, err := json.Marshal(createSubscriptionArgs{Subscription: encodeSubscription(argSubscription), Secret: encodeSecret(argSecret)})
	if err != nil {
		return webhook.CreateStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateSubscription, args)
	if err != nil {
		return webhook.CreateStoreRejected{Reason: guestError(err)}
	}
	var wire createResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return webhook.CreateStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateResult(wire)
	if err != nil {
		return webhook.CreateStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListSubscriptions(ctx context.Context, argOwner webhook.Owner, argPage core.Page) webhook.ListStoreResult {
	args, err := json.Marshal(listSubscriptionsArgs{Owner: encodeOwner(argOwner), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return webhook.ListStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListSubscriptions, args)
	if err != nil {
		return webhook.ListStoreRejected{Reason: guestError(err)}
	}
	var wire listResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return webhook.ListStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return webhook.ListStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RevokeSubscription(ctx context.Context, argOwner webhook.Owner, argID core.WebhookSubscriptionID) webhook.RevokeStoreResult {
	args, err := json.Marshal(revokeSubscriptionArgs{Owner: encodeOwner(argOwner), ID: corewire.EncodeWebhookSubscriptionID(argID)})
	if err != nil {
		return webhook.RevokeStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRevokeSubscription, args)
	if err != nil {
		return webhook.RevokeStoreRejected{Reason: guestError(err)}
	}
	var wire revokeResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return webhook.RevokeStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeRevokeResult(wire)
	if err != nil {
		return webhook.RevokeStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListDeliveries(ctx context.Context, argOwner webhook.Owner, argID core.WebhookSubscriptionID, argPage core.Page) webhook.ListDeliveriesStoreResult {
	args, err := json.Marshal(listDeliveriesArgs{Owner: encodeOwner(argOwner), ID: corewire.EncodeWebhookSubscriptionID(argID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return webhook.ListDeliveriesStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListDeliveries, args)
	if err != nil {
		return webhook.ListDeliveriesStoreRejected{Reason: guestError(err)}
	}
	var wire deliveriesResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return webhook.ListDeliveriesStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeDeliveriesResult(wire)
	if err != nil {
		return webhook.ListDeliveriesStoreRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "webhook bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// webhook.Store and the bridge is not regenerated, this fails to compile.
var _ webhook.Store = GuestStore{}
