// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package auditbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/audit"
	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/wasibridge/auditwire"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each audit.Store method on the wire.
const (
	methodRecord = "audit.Record"
	methodGet    = "audit.Get"
	methodList   = "audit.List"
)

type recordArgs struct {
	Event auditwire.EventWire `json:"event"`
}

type getArgs struct {
	ID string `json:"id"`
}

type listArgs struct {
	Filters listFiltersWire   `json:"filters"`
	Page    corewire.PageWire `json:"page"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store audit.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodRecord:
		var decoded recordArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("audit bridge: decode Record args: %w", err)
		}
		argEvent, err := auditwire.DecodeEvent(decoded.Event)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRecordResult(store.Record(ctx, argEvent)))
	case methodGet:
		var decoded getArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("audit bridge: decode Get args: %w", err)
		}
		argID, err := corewire.DecodeAuditEventID(decoded.ID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeGetResult(store.Get(ctx, argID)))
	case methodList:
		var decoded listArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("audit bridge: decode List args: %w", err)
		}
		argFilters, err := decodeListFilters(decoded.Filters)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.List(ctx, argFilters, argPage)))
	default:
		return nil, fmt.Errorf("audit bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements audit.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) Record(ctx context.Context, argEvent audit.Event) audit.RecordResult {
	args, err := json.Marshal(recordArgs{Event: auditwire.EncodeEvent(argEvent)})
	if err != nil {
		return audit.RecordRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRecord, args)
	if err != nil {
		return audit.RecordRejected{Reason: guestError(err)}
	}
	var wire recordResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return audit.RecordRejected{Reason: guestError(err)}
	}
	result, err := decodeRecordResult(wire)
	if err != nil {
		return audit.RecordRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) Get(ctx context.Context, argID core.AuditEventID) audit.GetResult {
	args, err := json.Marshal(getArgs{ID: corewire.EncodeAuditEventID(argID)})
	if err != nil {
		return audit.GetRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodGet, args)
	if err != nil {
		return audit.GetRejected{Reason: guestError(err)}
	}
	var wire getResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return audit.GetRejected{Reason: guestError(err)}
	}
	result, err := decodeGetResult(wire)
	if err != nil {
		return audit.GetRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) List(ctx context.Context, argFilters audit.ListFilters, argPage core.Page) audit.ListResult {
	args, err := json.Marshal(listArgs{Filters: encodeListFilters(argFilters), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return audit.ListRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodList, args)
	if err != nil {
		return audit.ListRejected{Reason: guestError(err)}
	}
	var wire listResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return audit.ListRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return audit.ListRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "audit bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// audit.Store and the bridge is not regenerated, this fails to compile.
var _ audit.Store = GuestStore{}
