// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package eventbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/event"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each event.Store method on the wire.
const (
	methodAppend           = "event.Append"
	methodListForRecipient = "event.ListForRecipient"
)

type appendArgs struct {
	Event      eventWire `json:"event"`
	Recipients []string  `json:"recipients"`
}

type listForRecipientArgs struct {
	UserID string            `json:"userid"`
	Filter cursorFilterWire  `json:"filter"`
	Page   corewire.PageWire `json:"page"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store event.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodAppend:
		var decoded appendArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("event bridge: decode Append args: %w", err)
		}
		argEvent, err := decodeEvent(decoded.Event)
		if err != nil {
			return nil, err
		}
		argRecipients, err := decodeRecipients(decoded.Recipients)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeAppendResult(store.Append(ctx, argEvent, argRecipients)))
	case methodListForRecipient:
		var decoded listForRecipientArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("event bridge: decode ListForRecipient args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argFilter, err := decodeCursorFilter(decoded.Filter)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.ListForRecipient(ctx, argUserID, argFilter, argPage)))
	default:
		return nil, fmt.Errorf("event bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements event.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) Append(ctx context.Context, argEvent event.Event, argRecipients event.Recipients) event.AppendStoreResult {
	args, err := json.Marshal(appendArgs{Event: encodeEvent(argEvent), Recipients: encodeRecipients(argRecipients)})
	if err != nil {
		return event.AppendStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodAppend, args)
	if err != nil {
		return event.AppendStoreRejected{Reason: guestError(err)}
	}
	var wire appendResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return event.AppendStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeAppendResult(wire)
	if err != nil {
		return event.AppendStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListForRecipient(ctx context.Context, argUserID core.UserID, argFilter event.CursorFilter, argPage core.Page) event.ListStoreResult {
	args, err := json.Marshal(listForRecipientArgs{UserID: corewire.EncodeUserID(argUserID), Filter: encodeCursorFilter(argFilter), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return event.ListStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListForRecipient, args)
	if err != nil {
		return event.ListStoreRejected{Reason: guestError(err)}
	}
	var wire listResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return event.ListStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return event.ListStoreRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "event bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// event.Store and the bridge is not regenerated, this fails to compile.
var _ event.Store = GuestStore{}
