// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package notificationbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/notification"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each notification.Store method on the wire.
const (
	methodCreate   = "notification.Create"
	methodList     = "notification.List"
	methodMarkRead = "notification.MarkRead"
)

type createArgs struct {
	Notification notificationWire `json:"notification"`
}

type listArgs struct {
	UserID string            `json:"userid"`
	Page   corewire.PageWire `json:"page"`
}

type markReadArgs struct {
	UserID string `json:"userid"`
	ID     string `json:"id"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store notification.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreate:
		var decoded createArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("notification bridge: decode Create args: %w", err)
		}
		argNotification, err := decodeNotification(decoded.Notification)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateResult(store.Create(ctx, argNotification)))
	case methodList:
		var decoded listArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("notification bridge: decode List args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.List(ctx, argUserID, argPage)))
	case methodMarkRead:
		var decoded markReadArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("notification bridge: decode MarkRead args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argID, err := corewire.DecodeNotificationID(decoded.ID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMarkReadResult(store.MarkRead(ctx, argUserID, argID)))
	default:
		return nil, fmt.Errorf("notification bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements notification.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) Create(ctx context.Context, argNotification notification.Notification) notification.CreateStoreResult {
	args, err := json.Marshal(createArgs{Notification: encodeNotification(argNotification)})
	if err != nil {
		return notification.CreateStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreate, args)
	if err != nil {
		return notification.CreateStoreRejected{Reason: guestError(err)}
	}
	var wire createResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return notification.CreateStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateResult(wire)
	if err != nil {
		return notification.CreateStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) List(ctx context.Context, argUserID core.UserID, argPage core.Page) notification.ListStoreResult {
	args, err := json.Marshal(listArgs{UserID: corewire.EncodeUserID(argUserID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return notification.ListStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodList, args)
	if err != nil {
		return notification.ListStoreRejected{Reason: guestError(err)}
	}
	var wire listResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return notification.ListStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return notification.ListStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) MarkRead(ctx context.Context, argUserID core.UserID, argID core.NotificationID) notification.MarkReadStoreResult {
	args, err := json.Marshal(markReadArgs{UserID: corewire.EncodeUserID(argUserID), ID: corewire.EncodeNotificationID(argID)})
	if err != nil {
		return notification.MarkReadStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodMarkRead, args)
	if err != nil {
		return notification.MarkReadStoreRejected{Reason: guestError(err)}
	}
	var wire markReadResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return notification.MarkReadStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeMarkReadResult(wire)
	if err != nil {
		return notification.MarkReadStoreRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "notification bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// notification.Store and the bridge is not regenerated, this fails to compile.
var _ notification.Store = GuestStore{}
