// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package authbridge

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/e6qu/sharecrop/internal/auth"
	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each auth.Store method on the wire.
const (
	methodCreateUserCredential         = "auth.CreateUserCredential"
	methodFindOrCreateExternalIdentity = "auth.FindOrCreateExternalIdentity"
	methodFindCredentialByEmail        = "auth.FindCredentialByEmail"
	methodFindCredentialByUserID       = "auth.FindCredentialByUserID"
	methodListUsers                    = "auth.ListUsers"
	methodUpdateUserEmail              = "auth.UpdateUserEmail"
	methodUpdatePassword               = "auth.UpdatePassword"
	methodDeactivateUser               = "auth.DeactivateUser"
	methodCreateGuestSubject           = "auth.CreateGuestSubject"
	methodStoreRefreshToken            = "auth.StoreRefreshToken"
	methodConsumeRefreshToken          = "auth.ConsumeRefreshToken"
	methodRevokeRefreshFamily          = "auth.RevokeRefreshFamily"
	methodStoreAccountToken            = "auth.StoreAccountToken"
	methodConsumeAccountToken          = "auth.ConsumeAccountToken"
)

type createUserCredentialArgs struct {
	UserID       string `json:"userid"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordhash"`
}

type findOrCreateExternalIdentityArgs struct {
	Identity externalIdentityWire `json:"identity"`
	Email    string               `json:"email"`
}

type findCredentialByEmailArgs struct {
	Email string `json:"email"`
}

type findCredentialByUserIDArgs struct {
	UserID string `json:"userid"`
}

type listUsersArgs struct {
	Query string            `json:"query"`
	Page  corewire.PageWire `json:"page"`
}

type updateUserEmailArgs struct {
	UserID string `json:"userid"`
	Email  string `json:"email"`
}

type updatePasswordArgs struct {
	UserID       string `json:"userid"`
	PasswordHash string `json:"passwordhash"`
}

type deactivateUserArgs struct {
	UserID string `json:"userid"`
}

type createGuestSubjectArgs struct {
	GuestID string `json:"guestid"`
}

type storeRefreshTokenArgs struct {
	Record refreshTokenRecordWire `json:"record"`
}

type consumeRefreshTokenArgs struct {
	Hash string `json:"hash"`
	Now  string `json:"now"`
}

type revokeRefreshFamilyArgs struct {
	Hash string `json:"hash"`
}

type storeAccountTokenArgs struct {
	UserID string           `json:"userid"`
	Kind   string           `json:"kind"`
	Token  accountTokenWire `json:"token"`
}

type consumeAccountTokenArgs struct {
	Kind string `json:"kind"`
	Hash string `json:"hash"`
	Now  string `json:"now"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store auth.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreateUserCredential:
		var decoded createUserCredentialArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode CreateUserCredential args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argEmail, err := decodeEmail(decoded.Email)
		if err != nil {
			return nil, err
		}
		argPasswordHash, err := decodePasswordHash(decoded.PasswordHash)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeStoreUserResult(store.CreateUserCredential(ctx, argUserID, argEmail, argPasswordHash)))
	case methodFindOrCreateExternalIdentity:
		var decoded findOrCreateExternalIdentityArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode FindOrCreateExternalIdentity args: %w", err)
		}
		argIdentity, err := decodeExternalIdentity(decoded.Identity)
		if err != nil {
			return nil, err
		}
		argEmail, err := decodeEmail(decoded.Email)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeExternalIdentityResult(store.FindOrCreateExternalIdentity(ctx, argIdentity, argEmail)))
	case methodFindCredentialByEmail:
		var decoded findCredentialByEmailArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode FindCredentialByEmail args: %w", err)
		}
		argEmail, err := decodeEmail(decoded.Email)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCredentialLookupResult(store.FindCredentialByEmail(ctx, argEmail)))
	case methodFindCredentialByUserID:
		var decoded findCredentialByUserIDArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode FindCredentialByUserID args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCredentialLookupResult(store.FindCredentialByUserID(ctx, argUserID)))
	case methodListUsers:
		var decoded listUsersArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode ListUsers args: %w", err)
		}
		argQuery, err := corewire.DecodeString(decoded.Query)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeUserDirectoryResult(store.ListUsers(ctx, argQuery, argPage)))
	case methodUpdateUserEmail:
		var decoded updateUserEmailArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode UpdateUserEmail args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argEmail, err := decodeEmail(decoded.Email)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeAccountMutationResult(store.UpdateUserEmail(ctx, argUserID, argEmail)))
	case methodUpdatePassword:
		var decoded updatePasswordArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode UpdatePassword args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argPasswordHash, err := decodePasswordHash(decoded.PasswordHash)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeAccountMutationResult(store.UpdatePassword(ctx, argUserID, argPasswordHash)))
	case methodDeactivateUser:
		var decoded deactivateUserArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode DeactivateUser args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeAccountMutationResult(store.DeactivateUser(ctx, argUserID)))
	case methodCreateGuestSubject:
		var decoded createGuestSubjectArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode CreateGuestSubject args: %w", err)
		}
		argGuestID, err := corewire.DecodeGuestID(decoded.GuestID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeStoreGuestResult(store.CreateGuestSubject(ctx, argGuestID)))
	case methodStoreRefreshToken:
		var decoded storeRefreshTokenArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode StoreRefreshToken args: %w", err)
		}
		argRecord, err := decodeRefreshTokenRecord(decoded.Record)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeStoreRefreshTokenResult(store.StoreRefreshToken(ctx, argRecord)))
	case methodConsumeRefreshToken:
		var decoded consumeRefreshTokenArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode ConsumeRefreshToken args: %w", err)
		}
		argHash, err := decodeRefreshTokenHash(decoded.Hash)
		if err != nil {
			return nil, err
		}
		argNow, err := corewire.DecodeTime(decoded.Now)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeConsumeRefreshTokenResult(store.ConsumeRefreshToken(ctx, argHash, argNow)))
	case methodRevokeRefreshFamily:
		var decoded revokeRefreshFamilyArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode RevokeRefreshFamily args: %w", err)
		}
		argHash, err := decodeRefreshTokenHash(decoded.Hash)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRevokeRefreshFamilyResult(store.RevokeRefreshFamily(ctx, argHash)))
	case methodStoreAccountToken:
		var decoded storeAccountTokenArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode StoreAccountToken args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argKind, err := decodeAccountTokenKind(decoded.Kind)
		if err != nil {
			return nil, err
		}
		argToken, err := decodeAccountToken(decoded.Token)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeAccountTokenStoreResult(store.StoreAccountToken(ctx, argUserID, argKind, argToken)))
	case methodConsumeAccountToken:
		var decoded consumeAccountTokenArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("auth bridge: decode ConsumeAccountToken args: %w", err)
		}
		argKind, err := decodeAccountTokenKind(decoded.Kind)
		if err != nil {
			return nil, err
		}
		argHash, err := decodeAccountTokenHash(decoded.Hash)
		if err != nil {
			return nil, err
		}
		argNow, err := corewire.DecodeTime(decoded.Now)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeAccountTokenConsumeResult(store.ConsumeAccountToken(ctx, argKind, argHash, argNow)))
	default:
		return nil, fmt.Errorf("auth bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements auth.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) CreateUserCredential(ctx context.Context, argUserID core.UserID, argEmail auth.EmailAddress, argPasswordHash auth.PasswordHash) auth.StoreUserResult {
	args, err := json.Marshal(createUserCredentialArgs{UserID: corewire.EncodeUserID(argUserID), Email: encodeEmail(argEmail), PasswordHash: encodePasswordHash(argPasswordHash)})
	if err != nil {
		return auth.StoreUserRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateUserCredential, args)
	if err != nil {
		return auth.StoreUserRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.StoreUserRejected{Reason: guestError(err)}
	}
	result, err := decodeStoreUserResult(wire)
	if err != nil {
		return auth.StoreUserRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FindOrCreateExternalIdentity(ctx context.Context, argIdentity auth.ExternalIdentity, argEmail auth.EmailAddress) auth.ExternalIdentityResult {
	args, err := json.Marshal(findOrCreateExternalIdentityArgs{Identity: encodeExternalIdentity(argIdentity), Email: encodeEmail(argEmail)})
	if err != nil {
		return auth.ExternalIdentityRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFindOrCreateExternalIdentity, args)
	if err != nil {
		return auth.ExternalIdentityRejected{Reason: guestError(err)}
	}
	var wire externalIdentityResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.ExternalIdentityRejected{Reason: guestError(err)}
	}
	result, err := decodeExternalIdentityResult(wire)
	if err != nil {
		return auth.ExternalIdentityRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FindCredentialByEmail(ctx context.Context, argEmail auth.EmailAddress) auth.CredentialLookupResult {
	args, err := json.Marshal(findCredentialByEmailArgs{Email: encodeEmail(argEmail)})
	if err != nil {
		return auth.CredentialLookupRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFindCredentialByEmail, args)
	if err != nil {
		return auth.CredentialLookupRejected{Reason: guestError(err)}
	}
	var wire credentialLookupResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.CredentialLookupRejected{Reason: guestError(err)}
	}
	result, err := decodeCredentialLookupResult(wire)
	if err != nil {
		return auth.CredentialLookupRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FindCredentialByUserID(ctx context.Context, argUserID core.UserID) auth.CredentialLookupResult {
	args, err := json.Marshal(findCredentialByUserIDArgs{UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return auth.CredentialLookupRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFindCredentialByUserID, args)
	if err != nil {
		return auth.CredentialLookupRejected{Reason: guestError(err)}
	}
	var wire credentialLookupResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.CredentialLookupRejected{Reason: guestError(err)}
	}
	result, err := decodeCredentialLookupResult(wire)
	if err != nil {
		return auth.CredentialLookupRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListUsers(ctx context.Context, argQuery string, argPage core.Page) auth.UserDirectoryResult {
	args, err := json.Marshal(listUsersArgs{Query: corewire.EncodeString(argQuery), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return auth.UserDirectoryRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListUsers, args)
	if err != nil {
		return auth.UserDirectoryRejected{Reason: guestError(err)}
	}
	var wire userDirectoryResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.UserDirectoryRejected{Reason: guestError(err)}
	}
	result, err := decodeUserDirectoryResult(wire)
	if err != nil {
		return auth.UserDirectoryRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) UpdateUserEmail(ctx context.Context, argUserID core.UserID, argEmail auth.EmailAddress) auth.AccountMutationResult {
	args, err := json.Marshal(updateUserEmailArgs{UserID: corewire.EncodeUserID(argUserID), Email: encodeEmail(argEmail)})
	if err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodUpdateUserEmail, args)
	if err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeAccountMutationResult(wire)
	if err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) UpdatePassword(ctx context.Context, argUserID core.UserID, argPasswordHash auth.PasswordHash) auth.AccountMutationResult {
	args, err := json.Marshal(updatePasswordArgs{UserID: corewire.EncodeUserID(argUserID), PasswordHash: encodePasswordHash(argPasswordHash)})
	if err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodUpdatePassword, args)
	if err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeAccountMutationResult(wire)
	if err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) DeactivateUser(ctx context.Context, argUserID core.UserID) auth.AccountMutationResult {
	args, err := json.Marshal(deactivateUserArgs{UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodDeactivateUser, args)
	if err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeAccountMutationResult(wire)
	if err != nil {
		return auth.AccountMutationRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) CreateGuestSubject(ctx context.Context, argGuestID core.GuestID) auth.StoreGuestResult {
	args, err := json.Marshal(createGuestSubjectArgs{GuestID: corewire.EncodeGuestID(argGuestID)})
	if err != nil {
		return auth.StoreGuestRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateGuestSubject, args)
	if err != nil {
		return auth.StoreGuestRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.StoreGuestRejected{Reason: guestError(err)}
	}
	result, err := decodeStoreGuestResult(wire)
	if err != nil {
		return auth.StoreGuestRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) StoreRefreshToken(ctx context.Context, argRecord auth.RefreshTokenRecord) auth.StoreRefreshTokenResult {
	args, err := json.Marshal(storeRefreshTokenArgs{Record: encodeRefreshTokenRecord(argRecord)})
	if err != nil {
		return auth.StoreRefreshTokenRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodStoreRefreshToken, args)
	if err != nil {
		return auth.StoreRefreshTokenRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.StoreRefreshTokenRejected{Reason: guestError(err)}
	}
	result, err := decodeStoreRefreshTokenResult(wire)
	if err != nil {
		return auth.StoreRefreshTokenRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ConsumeRefreshToken(ctx context.Context, argHash auth.RefreshTokenHash, argNow time.Time) auth.ConsumeRefreshTokenResult {
	args, err := json.Marshal(consumeRefreshTokenArgs{Hash: encodeRefreshTokenHash(argHash), Now: corewire.EncodeTime(argNow)})
	if err != nil {
		return auth.ConsumeRefreshTokenRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodConsumeRefreshToken, args)
	if err != nil {
		return auth.ConsumeRefreshTokenRejected{Reason: guestError(err)}
	}
	var wire consumeRefreshTokenResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.ConsumeRefreshTokenRejected{Reason: guestError(err)}
	}
	result, err := decodeConsumeRefreshTokenResult(wire)
	if err != nil {
		return auth.ConsumeRefreshTokenRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RevokeRefreshFamily(ctx context.Context, argHash auth.RefreshTokenHash) auth.RevokeRefreshFamilyResult {
	args, err := json.Marshal(revokeRefreshFamilyArgs{Hash: encodeRefreshTokenHash(argHash)})
	if err != nil {
		return auth.RevokeRefreshFamilyRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRevokeRefreshFamily, args)
	if err != nil {
		return auth.RevokeRefreshFamilyRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.RevokeRefreshFamilyRejected{Reason: guestError(err)}
	}
	result, err := decodeRevokeRefreshFamilyResult(wire)
	if err != nil {
		return auth.RevokeRefreshFamilyRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) StoreAccountToken(ctx context.Context, argUserID core.UserID, argKind auth.AccountTokenKind, argToken auth.AccountToken) auth.AccountTokenStoreResult {
	args, err := json.Marshal(storeAccountTokenArgs{UserID: corewire.EncodeUserID(argUserID), Kind: encodeAccountTokenKind(argKind), Token: encodeAccountToken(argToken)})
	if err != nil {
		return auth.AccountTokenStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodStoreAccountToken, args)
	if err != nil {
		return auth.AccountTokenStoreRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.AccountTokenStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeAccountTokenStoreResult(wire)
	if err != nil {
		return auth.AccountTokenStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ConsumeAccountToken(ctx context.Context, argKind auth.AccountTokenKind, argHash auth.AccountTokenHash, argNow time.Time) auth.AccountTokenConsumeResult {
	args, err := json.Marshal(consumeAccountTokenArgs{Kind: encodeAccountTokenKind(argKind), Hash: encodeAccountTokenHash(argHash), Now: corewire.EncodeTime(argNow)})
	if err != nil {
		return auth.AccountTokenConsumeRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodConsumeAccountToken, args)
	if err != nil {
		return auth.AccountTokenConsumeRejected{Reason: guestError(err)}
	}
	var wire accountTokenConsumeResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return auth.AccountTokenConsumeRejected{Reason: guestError(err)}
	}
	result, err := decodeAccountTokenConsumeResult(wire)
	if err != nil {
		return auth.AccountTokenConsumeRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "auth bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// auth.Store and the bridge is not regenerated, this fails to compile.
var _ auth.Store = GuestStore{}
