// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package submissionbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/submission"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each submission.Store method on the wire.
const (
	methodCreateSubmission        = "submission.CreateSubmission"
	methodFindByReceiptToken      = "submission.FindByReceiptToken"
	methodFindSubmission          = "submission.FindSubmission"
	methodListForTask             = "submission.ListForTask"
	methodListForSubmitter        = "submission.ListForSubmitter"
	methodCreateSubmissionComment = "submission.CreateSubmissionComment"
	methodListSubmissionComments  = "submission.ListSubmissionComments"
)

type createSubmissionArgs struct {
	SubmissionID    string                `json:"submissionid"`
	ReceiptID       string                `json:"receiptid"`
	ReceiptHash     string                `json:"receipthash"`
	Command         submitCommandWire     `json:"command"`
	State           string                `json:"state"`
	Validation      validationOutcomeWire `json:"validation"`
	SensitiveFields []sensitiveFieldWire  `json:"sensitivefields"`
}

type findByReceiptTokenArgs struct {
	ReceiptHash string `json:"receipthash"`
}

type findSubmissionArgs struct {
	SubmissionID string `json:"submissionid"`
}

type listForTaskArgs struct {
	TaskID string            `json:"taskid"`
	Page   corewire.PageWire `json:"page"`
}

type listForSubmitterArgs struct {
	UserID string            `json:"userid"`
	Page   corewire.PageWire `json:"page"`
}

type createSubmissionCommentArgs struct {
	Comment submissionCommentWire `json:"comment"`
}

type listSubmissionCommentsArgs struct {
	SubmissionID string `json:"submissionid"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store submission.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreateSubmission:
		var decoded createSubmissionArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("submission bridge: decode CreateSubmission args: %w", err)
		}
		argSubmissionID, err := corewire.DecodeSubmissionID(decoded.SubmissionID)
		if err != nil {
			return nil, err
		}
		argReceiptID, err := corewire.DecodeSubmissionReceiptTokenID(decoded.ReceiptID)
		if err != nil {
			return nil, err
		}
		argReceiptHash, err := decodeReceiptTokenHash(decoded.ReceiptHash)
		if err != nil {
			return nil, err
		}
		argCommand, err := decodeSubmitCommand(decoded.Command)
		if err != nil {
			return nil, err
		}
		argState, err := decodeState(decoded.State)
		if err != nil {
			return nil, err
		}
		argValidation, err := decodeValidationOutcome(decoded.Validation)
		if err != nil {
			return nil, err
		}
		argSensitiveFields, err := decodeSensitiveFields(decoded.SensitiveFields)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateSubmissionResult(store.CreateSubmission(ctx, argSubmissionID, argReceiptID, argReceiptHash, argCommand, argState, argValidation, argSensitiveFields)))
	case methodFindByReceiptToken:
		var decoded findByReceiptTokenArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("submission bridge: decode FindByReceiptToken args: %w", err)
		}
		argReceiptHash, err := decodeReceiptTokenHash(decoded.ReceiptHash)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeFindReceiptResult(store.FindByReceiptToken(ctx, argReceiptHash)))
	case methodFindSubmission:
		var decoded findSubmissionArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("submission bridge: decode FindSubmission args: %w", err)
		}
		argSubmissionID, err := corewire.DecodeSubmissionID(decoded.SubmissionID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeFindSubmissionResult(store.FindSubmission(ctx, argSubmissionID)))
	case methodListForTask:
		var decoded listForTaskArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("submission bridge: decode ListForTask args: %w", err)
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListSubmissionsResult(store.ListForTask(ctx, argTaskID, argPage)))
	case methodListForSubmitter:
		var decoded listForSubmitterArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("submission bridge: decode ListForSubmitter args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListSubmissionsResult(store.ListForSubmitter(ctx, argUserID, argPage)))
	case methodCreateSubmissionComment:
		var decoded createSubmissionCommentArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("submission bridge: decode CreateSubmissionComment args: %w", err)
		}
		argComment, err := decodeSubmissionComment(decoded.Comment)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateCommentResult(store.CreateSubmissionComment(ctx, argComment)))
	case methodListSubmissionComments:
		var decoded listSubmissionCommentsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("submission bridge: decode ListSubmissionComments args: %w", err)
		}
		argSubmissionID, err := corewire.DecodeSubmissionID(decoded.SubmissionID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListCommentsResult(store.ListSubmissionComments(ctx, argSubmissionID)))
	default:
		return nil, fmt.Errorf("submission bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements submission.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) CreateSubmission(ctx context.Context, argSubmissionID core.SubmissionID, argReceiptID core.SubmissionReceiptTokenID, argReceiptHash submission.ReceiptTokenHash, argCommand submission.SubmitCommand, argState submission.State, argValidation submission.ValidationOutcome, argSensitiveFields []submission.SensitiveField) submission.CreateSubmissionStoreResult {
	args, err := json.Marshal(createSubmissionArgs{SubmissionID: corewire.EncodeSubmissionID(argSubmissionID), ReceiptID: corewire.EncodeSubmissionReceiptTokenID(argReceiptID), ReceiptHash: encodeReceiptTokenHash(argReceiptHash), Command: encodeSubmitCommand(argCommand), State: encodeState(argState), Validation: encodeValidationOutcome(argValidation), SensitiveFields: encodeSensitiveFields(argSensitiveFields)})
	if err != nil {
		return submission.CreateSubmissionStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateSubmission, args)
	if err != nil {
		return submission.CreateSubmissionStoreRejected{Reason: guestError(err)}
	}
	var wire submissionResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return submission.CreateSubmissionStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateSubmissionResult(wire)
	if err != nil {
		return submission.CreateSubmissionStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FindByReceiptToken(ctx context.Context, argReceiptHash submission.ReceiptTokenHash) submission.FindReceiptStoreResult {
	args, err := json.Marshal(findByReceiptTokenArgs{ReceiptHash: encodeReceiptTokenHash(argReceiptHash)})
	if err != nil {
		return submission.ReceiptMissing{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFindByReceiptToken, args)
	if err != nil {
		return submission.ReceiptMissing{Reason: guestError(err)}
	}
	var wire submissionResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return submission.ReceiptMissing{Reason: guestError(err)}
	}
	result, err := decodeFindReceiptResult(wire)
	if err != nil {
		return submission.ReceiptMissing{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FindSubmission(ctx context.Context, argSubmissionID core.SubmissionID) submission.FindSubmissionStoreResult {
	args, err := json.Marshal(findSubmissionArgs{SubmissionID: corewire.EncodeSubmissionID(argSubmissionID)})
	if err != nil {
		return submission.FindSubmissionStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFindSubmission, args)
	if err != nil {
		return submission.FindSubmissionStoreRejected{Reason: guestError(err)}
	}
	var wire submissionResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return submission.FindSubmissionStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeFindSubmissionResult(wire)
	if err != nil {
		return submission.FindSubmissionStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListForTask(ctx context.Context, argTaskID core.TaskID, argPage core.Page) submission.ListSubmissionsStoreResult {
	args, err := json.Marshal(listForTaskArgs{TaskID: corewire.EncodeTaskID(argTaskID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return submission.ListSubmissionsStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListForTask, args)
	if err != nil {
		return submission.ListSubmissionsStoreRejected{Reason: guestError(err)}
	}
	var wire submissionsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return submission.ListSubmissionsStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListSubmissionsResult(wire)
	if err != nil {
		return submission.ListSubmissionsStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListForSubmitter(ctx context.Context, argUserID core.UserID, argPage core.Page) submission.ListSubmissionsStoreResult {
	args, err := json.Marshal(listForSubmitterArgs{UserID: corewire.EncodeUserID(argUserID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return submission.ListSubmissionsStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListForSubmitter, args)
	if err != nil {
		return submission.ListSubmissionsStoreRejected{Reason: guestError(err)}
	}
	var wire submissionsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return submission.ListSubmissionsStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListSubmissionsResult(wire)
	if err != nil {
		return submission.ListSubmissionsStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) CreateSubmissionComment(ctx context.Context, argComment submission.SubmissionComment) submission.CreateSubmissionCommentStoreResult {
	args, err := json.Marshal(createSubmissionCommentArgs{Comment: encodeSubmissionComment(argComment)})
	if err != nil {
		return submission.CreateSubmissionCommentStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateSubmissionComment, args)
	if err != nil {
		return submission.CreateSubmissionCommentStoreRejected{Reason: guestError(err)}
	}
	var wire submissionCommentResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return submission.CreateSubmissionCommentStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateCommentResult(wire)
	if err != nil {
		return submission.CreateSubmissionCommentStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListSubmissionComments(ctx context.Context, argSubmissionID core.SubmissionID) submission.ListSubmissionCommentsStoreResult {
	args, err := json.Marshal(listSubmissionCommentsArgs{SubmissionID: corewire.EncodeSubmissionID(argSubmissionID)})
	if err != nil {
		return submission.ListSubmissionCommentsStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListSubmissionComments, args)
	if err != nil {
		return submission.ListSubmissionCommentsStoreRejected{Reason: guestError(err)}
	}
	var wire submissionCommentsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return submission.ListSubmissionCommentsStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListCommentsResult(wire)
	if err != nil {
		return submission.ListSubmissionCommentsStoreRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "submission bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// submission.Store and the bridge is not regenerated, this fails to compile.
var _ submission.Store = GuestStore{}
