// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package agentbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/agent"
	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each agent.Store method on the wire.
const (
	methodCreateCredential = "agent.CreateCredential"
	methodVerifyCredential = "agent.VerifyCredential"
	methodListCredentials  = "agent.ListCredentials"
	methodRevokeCredential = "agent.RevokeCredential"
)

type createCredentialArgs struct {
	Credential credentialWire `json:"credential"`
	SecretHash string         `json:"secrethash"`
}

type verifyCredentialArgs struct {
	SecretHash string `json:"secrethash"`
}

type listCredentialsArgs struct {
	UserID string            `json:"userid"`
	Page   corewire.PageWire `json:"page"`
}

type revokeCredentialArgs struct {
	UserID string `json:"userid"`
	ID     string `json:"id"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store agent.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreateCredential:
		var decoded createCredentialArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("agent bridge: decode CreateCredential args: %w", err)
		}
		argCredential, err := decodeCredential(decoded.Credential)
		if err != nil {
			return nil, err
		}
		argSecretHash, err := decodeSecretHash(decoded.SecretHash)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateResult(store.CreateCredential(ctx, argCredential, argSecretHash)))
	case methodVerifyCredential:
		var decoded verifyCredentialArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("agent bridge: decode VerifyCredential args: %w", err)
		}
		argSecretHash, err := decodeSecretHash(decoded.SecretHash)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeVerifyResult(store.VerifyCredential(ctx, argSecretHash)))
	case methodListCredentials:
		var decoded listCredentialsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("agent bridge: decode ListCredentials args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.ListCredentials(ctx, argUserID, argPage)))
	case methodRevokeCredential:
		var decoded revokeCredentialArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("agent bridge: decode RevokeCredential args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argID, err := corewire.DecodeAgentCredentialID(decoded.ID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRevokeResult(store.RevokeCredential(ctx, argUserID, argID)))
	default:
		return nil, fmt.Errorf("agent bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements agent.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) CreateCredential(ctx context.Context, argCredential agent.Credential, argSecretHash agent.SecretHash) agent.CreateStoreResult {
	args, err := json.Marshal(createCredentialArgs{Credential: encodeCredential(argCredential), SecretHash: encodeSecretHash(argSecretHash)})
	if err != nil {
		return agent.CreateStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateCredential, args)
	if err != nil {
		return agent.CreateStoreRejected{Reason: guestError(err)}
	}
	var wire createResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return agent.CreateStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateResult(wire)
	if err != nil {
		return agent.CreateStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) VerifyCredential(ctx context.Context, argSecretHash agent.SecretHash) agent.VerifyStoreResult {
	args, err := json.Marshal(verifyCredentialArgs{SecretHash: encodeSecretHash(argSecretHash)})
	if err != nil {
		return agent.VerifyStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodVerifyCredential, args)
	if err != nil {
		return agent.VerifyStoreRejected{Reason: guestError(err)}
	}
	var wire credentialResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return agent.VerifyStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeVerifyResult(wire)
	if err != nil {
		return agent.VerifyStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListCredentials(ctx context.Context, argUserID core.UserID, argPage core.Page) agent.ListStoreResult {
	args, err := json.Marshal(listCredentialsArgs{UserID: corewire.EncodeUserID(argUserID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return agent.ListStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListCredentials, args)
	if err != nil {
		return agent.ListStoreRejected{Reason: guestError(err)}
	}
	var wire listResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return agent.ListStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return agent.ListStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RevokeCredential(ctx context.Context, argUserID core.UserID, argID core.AgentCredentialID) agent.RevokeStoreResult {
	args, err := json.Marshal(revokeCredentialArgs{UserID: corewire.EncodeUserID(argUserID), ID: corewire.EncodeAgentCredentialID(argID)})
	if err != nil {
		return agent.RevokeStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRevokeCredential, args)
	if err != nil {
		return agent.RevokeStoreRejected{Reason: guestError(err)}
	}
	var wire credentialResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return agent.RevokeStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeRevokeResult(wire)
	if err != nil {
		return agent.RevokeStoreRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "agent bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// agent.Store and the bridge is not regenerated, this fails to compile.
var _ agent.Store = GuestStore{}
