// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package savedqueueviewbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/http"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each httpserver.SavedQueueViewService method on the wire.
const (
	methodList   = "savedqueueview.List"
	methodUpsert = "savedqueueview.Upsert"
)

type listArgs struct {
	UserID string `json:"userid"`
	Scope  string `json:"scope"`
}

type upsertArgs struct {
	View savedQueueViewWire `json:"view"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store httpserver.SavedQueueViewService, method string, args []byte) ([]byte, error) {
	switch method {
	case methodList:
		var decoded listArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("savedqueueview bridge: decode List args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argScope, err := corewire.DecodeString(decoded.Scope)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.List(ctx, argUserID, argScope)))
	case methodUpsert:
		var decoded upsertArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("savedqueueview bridge: decode Upsert args: %w", err)
		}
		argView, err := decodeView(decoded.View)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMutationResult(store.Upsert(ctx, argView)))
	default:
		return nil, fmt.Errorf("savedqueueview bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements httpserver.SavedQueueViewService by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) List(ctx context.Context, argUserID core.UserID, argScope string) httpserver.SavedQueueViewsListResult {
	args, err := json.Marshal(listArgs{UserID: corewire.EncodeUserID(argUserID), Scope: corewire.EncodeString(argScope)})
	if err != nil {
		return httpserver.SavedQueueViewsListRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodList, args)
	if err != nil {
		return httpserver.SavedQueueViewsListRejected{Reason: guestError(err)}
	}
	var wire viewsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.SavedQueueViewsListRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return httpserver.SavedQueueViewsListRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) Upsert(ctx context.Context, argView httpserver.SavedQueueView) httpserver.SavedQueueViewMutationResult {
	args, err := json.Marshal(upsertArgs{View: encodeView(argView)})
	if err != nil {
		return httpserver.SavedQueueViewSaveRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodUpsert, args)
	if err != nil {
		return httpserver.SavedQueueViewSaveRejected{Reason: guestError(err)}
	}
	var wire viewResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.SavedQueueViewSaveRejected{Reason: guestError(err)}
	}
	result, err := decodeMutationResult(wire)
	if err != nil {
		return httpserver.SavedQueueViewSaveRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "savedqueueview bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// httpserver.SavedQueueViewService and the bridge is not regenerated, this fails to compile.
var _ httpserver.SavedQueueViewService = GuestStore{}
