//go:build integration

package integration_test

import (
	"context"
	"testing"
	"time"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/db"
	"github.com/e6qu/sharecrop/internal/notification"
	"github.com/e6qu/sharecrop/internal/notification/notificationtest"
	"github.com/e6qu/sharecrop/internal/wasibridge/notificationbridge"
	"github.com/e6qu/sharecrop/internal/wasibridge/rpc"
)

// TestNotificationBridgeDualRun exercises the notification Store through both
// the direct-db path and the compiled wasip1 guest + host bridge, proving the
// generated notification bridge (a second store, generated by the same tooling
// as audit) behaves identically to internal/db.
func TestNotificationBridgeDualRun(t *testing.T) {
	ctx := context.Background()
	pool := newPool(t)
	dbStore := db.NewNotificationStore(pool)

	guestWASM, err := compileWASIGuest(t, "github.com/e6qu/sharecrop/cmd/sharecrop-wasi-store-guest")
	if err != nil {
		t.Fatalf("compile store guest: %v", err)
	}
	host, err := rpc.NewHost(ctx, guestWASM, func(ctx context.Context, method string, args []byte) ([]byte, error) {
		return notificationbridge.Dispatch(ctx, dbStore, method, args)
	})
	if err != nil {
		t.Fatalf("new host: %v", err)
	}
	t.Cleanup(func() { _ = host.Close(ctx) })

	bridgeStore := notificationbridge.NewGuestStore(func(method string, args []byte) ([]byte, error) {
		return host.Call(ctx, method, args)
	})

	recipient := createUser(t, pool, "notif-recipient")
	actor := createUser(t, pool, "notif-actor")
	page := requirePage(t, 50, 0)

	t.Run("create: writing through the bridge persists to postgres", func(t *testing.T) {
		value := buildNotification(t, recipient, actor)
		if _, matched := bridgeStore.Create(ctx, value).(notification.CreateStoreAccepted); !matched {
			t.Fatalf("bridge create did not report CreateStoreAccepted")
		}
		listed := requireNotificationsListed(t, dbStore.List(ctx, recipient, page))
		if !containsNotification(listed, value.ID) {
			t.Errorf("bridge-created notification %s was not persisted", value.ID)
		}
	})

	t.Run("list: bridge listing matches a direct store call", func(t *testing.T) {
		viaBridge := requireNotificationsListed(t, bridgeStore.List(ctx, recipient, page))
		direct := requireNotificationsListed(t, dbStore.List(ctx, recipient, page))
		if len(viaBridge) != len(direct) {
			t.Fatalf("list counts: bridge %d, direct %d", len(viaBridge), len(direct))
		}
		for i := range direct {
			if diff := notificationtest.NotificationDiff(viaBridge[i], direct[i]); diff != "" {
				t.Errorf("notification %d mismatch: %s", i, diff)
			}
		}
	})

	t.Run("mark read: bridge matches, missing rejects the same way", func(t *testing.T) {
		seeded := seedNotification(t, ctx, dbStore, recipient, actor)

		marked := bridgeStore.MarkRead(ctx, recipient, seeded.ID)
		accepted, matched := marked.(notification.MarkReadStoreAccepted)
		if !matched {
			t.Fatalf("bridge mark-read result = %T, want MarkReadStoreAccepted", marked)
		}
		if accepted.Value.State.String() != notification.StateRead.String() {
			t.Errorf("marked state = %s, want read", accepted.Value.State)
		}

		missing := newNotificationID(t)
		bridgeReason := requireMarkReadRejected(t, bridgeStore.MarkRead(ctx, recipient, missing))
		directReason := requireMarkReadRejected(t, dbStore.MarkRead(ctx, recipient, missing))
		if bridgeReason.Code() != core.ErrorCodeNotFound || directReason.Code() != core.ErrorCodeNotFound {
			t.Errorf("rejection codes: bridge %s, direct %s, want not_found", bridgeReason.Code(), directReason.Code())
		}
	})
}

func newNotificationID(t *testing.T) core.NotificationID {
	t.Helper()
	created, matched := core.NewNotificationID().(core.NotificationIDCreated)
	if !matched {
		t.Fatalf("notification id rejected")
	}
	return created.Value
}

func requirePage(t *testing.T, limit, offset int) core.Page {
	t.Helper()
	accepted, matched := core.NewPage(limit, offset).(core.PageAccepted)
	if !matched {
		t.Fatalf("page rejected")
	}
	return accepted.Value
}

func buildNotification(t *testing.T, recipient, actor core.UserID) notification.Notification {
	t.Helper()
	return notification.Notification{
		ID:          newNotificationID(t),
		RecipientID: recipient,
		ActorID:     actor,
		Kind:        notification.KindSubmissionAccepted,
		Subject:     notification.Subject{Kind: "submission", ID: "sub-" + newNotificationID(t).String()},
		State:       notification.StateUnread,
		Metadata:    notification.EmptyMetadata(),
		CreatedAt:   time.Now().UTC().Round(time.Microsecond),
	}
}

func seedNotification(t *testing.T, ctx context.Context, store db.NotificationStore, recipient, actor core.UserID) notification.Notification {
	t.Helper()
	value := buildNotification(t, recipient, actor)
	if _, matched := store.Create(ctx, value).(notification.CreateStoreAccepted); !matched {
		t.Fatalf("seed create rejected")
	}
	return value
}

func requireNotificationsListed(t *testing.T, result notification.ListStoreResult) []notification.Notification {
	t.Helper()
	listed, matched := result.(notification.ListStoreAccepted)
	if !matched {
		t.Fatalf("list result = %T, want ListStoreAccepted", result)
	}
	return listed.Values
}

func requireMarkReadRejected(t *testing.T, result notification.MarkReadStoreResult) core.DomainError {
	t.Helper()
	rejected, matched := result.(notification.MarkReadStoreRejected)
	if !matched {
		t.Fatalf("mark-read result = %T, want MarkReadStoreRejected", result)
	}
	return rejected.Reason
}

func containsNotification(values []notification.Notification, id core.NotificationID) bool {
	for index := range values {
		if values[index].ID == id {
			return true
		}
	}
	return false
}
