// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package ledgerbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/ledger"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each ledger.Store method on the wire.
const (
	methodFundTask                 = "ledger.FundTask"
	methodFundTaskFromOrganization = "ledger.FundTaskFromOrganization"
	methodAcceptSubmission         = "ledger.AcceptSubmission"
	methodRequestChanges           = "ledger.RequestChanges"
	methodRejectSubmission         = "ledger.RejectSubmission"
	methodRefundTask               = "ledger.RefundTask"
	methodTaskAllocatedCredits     = "ledger.TaskAllocatedCredits"
	methodBalance                  = "ledger.Balance"
	methodOrganizationBalance      = "ledger.OrganizationBalance"
	methodListEntries              = "ledger.ListEntries"
	methodListOrganizationEntries  = "ledger.ListOrganizationEntries"
)

type fundTaskArgs struct {
	FundCommand fundCommandWire `json:"fundcommand"`
}

type fundTaskFromOrganizationArgs struct {
	OrgFundCommand orgFundCommandWire `json:"orgfundcommand"`
}

type acceptSubmissionArgs struct {
	AcceptCommand acceptCommandWire `json:"acceptcommand"`
}

type requestChangesArgs struct {
	RequestChangesCommand requestChangesCommandWire `json:"requestchangescommand"`
}

type rejectSubmissionArgs struct {
	RejectCommand rejectCommandWire `json:"rejectcommand"`
}

type refundTaskArgs struct {
	RefundCommand refundCommandWire `json:"refundcommand"`
}

type taskAllocatedCreditsArgs struct {
	TaskID string `json:"taskid"`
}

type balanceArgs struct {
	UserID string `json:"userid"`
}

type organizationBalanceArgs struct {
	OrganizationID string `json:"organizationid"`
}

type listEntriesArgs struct {
	UserID string            `json:"userid"`
	Page   corewire.PageWire `json:"page"`
}

type listOrganizationEntriesArgs struct {
	OrganizationID string            `json:"organizationid"`
	Page           corewire.PageWire `json:"page"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store ledger.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodFundTask:
		var decoded fundTaskArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode FundTask args: %w", err)
		}
		argFundCommand, err := decodeFundCommand(decoded.FundCommand)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeFundResult(store.FundTask(ctx, argFundCommand)))
	case methodFundTaskFromOrganization:
		var decoded fundTaskFromOrganizationArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode FundTaskFromOrganization args: %w", err)
		}
		argOrgFundCommand, err := decodeOrgFundCommand(decoded.OrgFundCommand)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeFundResult(store.FundTaskFromOrganization(ctx, argOrgFundCommand)))
	case methodAcceptSubmission:
		var decoded acceptSubmissionArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode AcceptSubmission args: %w", err)
		}
		argAcceptCommand, err := decodeAcceptCommand(decoded.AcceptCommand)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeAcceptResult(store.AcceptSubmission(ctx, argAcceptCommand)))
	case methodRequestChanges:
		var decoded requestChangesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode RequestChanges args: %w", err)
		}
		argRequestChangesCommand, err := decodeRequestChangesCommand(decoded.RequestChangesCommand)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRequestChangesResult(store.RequestChanges(ctx, argRequestChangesCommand)))
	case methodRejectSubmission:
		var decoded rejectSubmissionArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode RejectSubmission args: %w", err)
		}
		argRejectCommand, err := decodeRejectCommand(decoded.RejectCommand)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRejectResult(store.RejectSubmission(ctx, argRejectCommand)))
	case methodRefundTask:
		var decoded refundTaskArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode RefundTask args: %w", err)
		}
		argRefundCommand, err := decodeRefundCommand(decoded.RefundCommand)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRefundResult(store.RefundTask(ctx, argRefundCommand)))
	case methodTaskAllocatedCredits:
		var decoded taskAllocatedCreditsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode TaskAllocatedCredits args: %w", err)
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeTaskAllocatedResult(store.TaskAllocatedCredits(ctx, argTaskID)))
	case methodBalance:
		var decoded balanceArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode Balance args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeBalanceResult(store.Balance(ctx, argUserID)))
	case methodOrganizationBalance:
		var decoded organizationBalanceArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode OrganizationBalance args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeBalanceResult(store.OrganizationBalance(ctx, argOrganizationID)))
	case methodListEntries:
		var decoded listEntriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode ListEntries args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListEntriesResult(store.ListEntries(ctx, argUserID, argPage)))
	case methodListOrganizationEntries:
		var decoded listOrganizationEntriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("ledger bridge: decode ListOrganizationEntries args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListEntriesResult(store.ListOrganizationEntries(ctx, argOrganizationID, argPage)))
	default:
		return nil, fmt.Errorf("ledger bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements ledger.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) FundTask(ctx context.Context, argFundCommand ledger.FundStoreCommand) ledger.FundResult {
	args, err := json.Marshal(fundTaskArgs{FundCommand: encodeFundCommand(argFundCommand)})
	if err != nil {
		return ledger.FundRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFundTask, args)
	if err != nil {
		return ledger.FundRejected{Reason: guestError(err)}
	}
	var wire fundResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.FundRejected{Reason: guestError(err)}
	}
	result, err := decodeFundResult(wire)
	if err != nil {
		return ledger.FundRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FundTaskFromOrganization(ctx context.Context, argOrgFundCommand ledger.OrganizationFundStoreCommand) ledger.FundResult {
	args, err := json.Marshal(fundTaskFromOrganizationArgs{OrgFundCommand: encodeOrgFundCommand(argOrgFundCommand)})
	if err != nil {
		return ledger.FundRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFundTaskFromOrganization, args)
	if err != nil {
		return ledger.FundRejected{Reason: guestError(err)}
	}
	var wire fundResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.FundRejected{Reason: guestError(err)}
	}
	result, err := decodeFundResult(wire)
	if err != nil {
		return ledger.FundRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) AcceptSubmission(ctx context.Context, argAcceptCommand ledger.AcceptStoreCommand) ledger.AcceptResult {
	args, err := json.Marshal(acceptSubmissionArgs{AcceptCommand: encodeAcceptCommand(argAcceptCommand)})
	if err != nil {
		return ledger.AcceptRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodAcceptSubmission, args)
	if err != nil {
		return ledger.AcceptRejected{Reason: guestError(err)}
	}
	var wire reviewedSubmissionWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.AcceptRejected{Reason: guestError(err)}
	}
	result, err := decodeAcceptResult(wire)
	if err != nil {
		return ledger.AcceptRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RequestChanges(ctx context.Context, argRequestChangesCommand ledger.RequestChangesStoreCommand) ledger.RequestChangesResult {
	args, err := json.Marshal(requestChangesArgs{RequestChangesCommand: encodeRequestChangesCommand(argRequestChangesCommand)})
	if err != nil {
		return ledger.RequestChangesRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRequestChanges, args)
	if err != nil {
		return ledger.RequestChangesRejected{Reason: guestError(err)}
	}
	var wire changesRequestedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.RequestChangesRejected{Reason: guestError(err)}
	}
	result, err := decodeRequestChangesResult(wire)
	if err != nil {
		return ledger.RequestChangesRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RejectSubmission(ctx context.Context, argRejectCommand ledger.RejectStoreCommand) ledger.RejectResult {
	args, err := json.Marshal(rejectSubmissionArgs{RejectCommand: encodeRejectCommand(argRejectCommand)})
	if err != nil {
		return ledger.RejectRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRejectSubmission, args)
	if err != nil {
		return ledger.RejectRejected{Reason: guestError(err)}
	}
	var wire reviewedSubmissionWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.RejectRejected{Reason: guestError(err)}
	}
	result, err := decodeRejectResult(wire)
	if err != nil {
		return ledger.RejectRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RefundTask(ctx context.Context, argRefundCommand ledger.RefundStoreCommand) ledger.RefundResult {
	args, err := json.Marshal(refundTaskArgs{RefundCommand: encodeRefundCommand(argRefundCommand)})
	if err != nil {
		return ledger.RefundRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRefundTask, args)
	if err != nil {
		return ledger.RefundRejected{Reason: guestError(err)}
	}
	var wire fundResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.RefundRejected{Reason: guestError(err)}
	}
	result, err := decodeRefundResult(wire)
	if err != nil {
		return ledger.RefundRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) TaskAllocatedCredits(ctx context.Context, argTaskID core.TaskID) ledger.TaskAllocatedResult {
	args, err := json.Marshal(taskAllocatedCreditsArgs{TaskID: corewire.EncodeTaskID(argTaskID)})
	if err != nil {
		return ledger.TaskAllocatedRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodTaskAllocatedCredits, args)
	if err != nil {
		return ledger.TaskAllocatedRejected{Reason: guestError(err)}
	}
	var wire taskAllocatedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.TaskAllocatedRejected{Reason: guestError(err)}
	}
	result, err := decodeTaskAllocatedResult(wire)
	if err != nil {
		return ledger.TaskAllocatedRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) Balance(ctx context.Context, argUserID core.UserID) ledger.BalanceResult {
	args, err := json.Marshal(balanceArgs{UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return ledger.BalanceRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodBalance, args)
	if err != nil {
		return ledger.BalanceRejected{Reason: guestError(err)}
	}
	var wire balanceWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.BalanceRejected{Reason: guestError(err)}
	}
	result, err := decodeBalanceResult(wire)
	if err != nil {
		return ledger.BalanceRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) OrganizationBalance(ctx context.Context, argOrganizationID core.OrganizationID) ledger.BalanceResult {
	args, err := json.Marshal(organizationBalanceArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID)})
	if err != nil {
		return ledger.BalanceRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodOrganizationBalance, args)
	if err != nil {
		return ledger.BalanceRejected{Reason: guestError(err)}
	}
	var wire balanceWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.BalanceRejected{Reason: guestError(err)}
	}
	result, err := decodeBalanceResult(wire)
	if err != nil {
		return ledger.BalanceRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListEntries(ctx context.Context, argUserID core.UserID, argPage core.Page) ledger.ListEntriesResult {
	args, err := json.Marshal(listEntriesArgs{UserID: corewire.EncodeUserID(argUserID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return ledger.ListEntriesRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListEntries, args)
	if err != nil {
		return ledger.ListEntriesRejected{Reason: guestError(err)}
	}
	var wire entriesWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.ListEntriesRejected{Reason: guestError(err)}
	}
	result, err := decodeListEntriesResult(wire)
	if err != nil {
		return ledger.ListEntriesRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListOrganizationEntries(ctx context.Context, argOrganizationID core.OrganizationID, argPage core.Page) ledger.ListEntriesResult {
	args, err := json.Marshal(listOrganizationEntriesArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return ledger.ListEntriesRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListOrganizationEntries, args)
	if err != nil {
		return ledger.ListEntriesRejected{Reason: guestError(err)}
	}
	var wire entriesWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return ledger.ListEntriesRejected{Reason: guestError(err)}
	}
	result, err := decodeListEntriesResult(wire)
	if err != nil {
		return ledger.ListEntriesRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "ledger bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// ledger.Store and the bridge is not regenerated, this fails to compile.
var _ ledger.Store = GuestStore{}
