// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package taskbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/task"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each task.Store method on the wire.
const (
	methodCreateTask                 = "task.CreateTask"
	methodFindTask                   = "task.FindTask"
	methodChangeTaskState            = "task.ChangeTaskState"
	methodListTasks                  = "task.ListTasks"
	methodListSeries                 = "task.ListSeries"
	methodFindSeries                 = "task.FindSeries"
	methodCreateSeries               = "task.CreateSeries"
	methodUpdateSeries               = "task.UpdateSeries"
	methodUpdateSeriesState          = "task.UpdateSeriesState"
	methodAddTaskToSeries            = "task.AddTaskToSeries"
	methodRemoveTaskFromSeries       = "task.RemoveTaskFromSeries"
	methodReorderSeries              = "task.ReorderSeries"
	methodCreateSeriesComment        = "task.CreateSeriesComment"
	methodListSeriesComments         = "task.ListSeriesComments"
	methodCreateTaskComment          = "task.CreateTaskComment"
	methodListTaskComments           = "task.ListTaskComments"
	methodCreateReservation          = "task.CreateReservation"
	methodChangeReservationState     = "task.ChangeReservationState"
	methodListReservations           = "task.ListReservations"
	methodCheckSubmissionEligibility = "task.CheckSubmissionEligibility"
)

type createTaskArgs struct {
	SeriesID string            `json:"seriesid"`
	TaskID   string            `json:"taskid"`
	Command  createCommandWire `json:"command"`
}

type findTaskArgs struct {
	TaskID string `json:"taskid"`
}

type changeTaskStateArgs struct {
	TaskID string `json:"taskid"`
	State  string `json:"state"`
}

type listTasksArgs struct {
	Scope   listScopeWire     `json:"scope"`
	Filters listFiltersWire   `json:"filters"`
	Page    corewire.PageWire `json:"page"`
}

type listSeriesArgs struct {
	UserID string            `json:"userid"`
	Page   corewire.PageWire `json:"page"`
}

type findSeriesArgs struct {
	SeriesID string `json:"seriesid"`
}

type createSeriesArgs struct {
	Series seriesWire `json:"series"`
}

type updateSeriesArgs struct {
	SeriesID          string `json:"seriesid"`
	SeriesTitle       string `json:"seriestitle"`
	SeriesDescription string `json:"seriesdescription"`
}

type updateSeriesStateArgs struct {
	SeriesID    string `json:"seriesid"`
	SeriesState string `json:"seriesstate"`
}

type addTaskToSeriesArgs struct {
	SeriesID string `json:"seriesid"`
	TaskID   string `json:"taskid"`
}

type removeTaskFromSeriesArgs struct {
	SeriesID string `json:"seriesid"`
	TaskID   string `json:"taskid"`
}

type reorderSeriesArgs struct {
	SeriesID string   `json:"seriesid"`
	TaskIDs  []string `json:"taskids"`
}

type createSeriesCommentArgs struct {
	SeriesComment seriesCommentWire `json:"seriescomment"`
}

type listSeriesCommentsArgs struct {
	SeriesID string `json:"seriesid"`
}

type createTaskCommentArgs struct {
	TaskComment taskCommentWire `json:"taskcomment"`
}

type listTaskCommentsArgs struct {
	TaskID string `json:"taskid"`
}

type createReservationArgs struct {
	ReservationID string                 `json:"reservationid"`
	Command       reservationCommandWire `json:"command"`
}

type changeReservationStateArgs struct {
	TaskID           string `json:"taskid"`
	ReservationID    string `json:"reservationid"`
	ReservationState string `json:"reservationstate"`
}

type listReservationsArgs struct {
	TaskID string `json:"taskid"`
}

type checkSubmissionEligibilityArgs struct {
	TaskID string `json:"taskid"`
	UserID string `json:"userid"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store task.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreateTask:
		var decoded createTaskArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode CreateTask args: %w", err)
		}
		argSeriesID, err := corewire.DecodeTaskSeriesID(decoded.SeriesID)
		if err != nil {
			return nil, err
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		argCommand, err := decodeCreateCommand(decoded.Command)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateTaskResult(store.CreateTask(ctx, argSeriesID, argTaskID, argCommand)))
	case methodFindTask:
		var decoded findTaskArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode FindTask args: %w", err)
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeFindTaskResult(store.FindTask(ctx, argTaskID)))
	case methodChangeTaskState:
		var decoded changeTaskStateArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode ChangeTaskState args: %w", err)
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		argState, err := decodeState(decoded.State)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeChangeTaskStateResult(store.ChangeTaskState(ctx, argTaskID, argState)))
	case methodListTasks:
		var decoded listTasksArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode ListTasks args: %w", err)
		}
		argScope, err := decodeListScope(decoded.Scope)
		if err != nil {
			return nil, err
		}
		argFilters, err := decodeListFilters(decoded.Filters)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListTasksResult(store.ListTasks(ctx, argScope, argFilters, argPage)))
	case methodListSeries:
		var decoded listSeriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode ListSeries args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListSeriesResult(store.ListSeries(ctx, argUserID, argPage)))
	case methodFindSeries:
		var decoded findSeriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode FindSeries args: %w", err)
		}
		argSeriesID, err := corewire.DecodeTaskSeriesID(decoded.SeriesID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeFindSeriesResult(store.FindSeries(ctx, argSeriesID)))
	case methodCreateSeries:
		var decoded createSeriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode CreateSeries args: %w", err)
		}
		argSeries, err := decodeSeries(decoded.Series)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeSeriesMutationResult(store.CreateSeries(ctx, argSeries)))
	case methodUpdateSeries:
		var decoded updateSeriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode UpdateSeries args: %w", err)
		}
		argSeriesID, err := corewire.DecodeTaskSeriesID(decoded.SeriesID)
		if err != nil {
			return nil, err
		}
		argSeriesTitle, err := decodeSeriesTitle(decoded.SeriesTitle)
		if err != nil {
			return nil, err
		}
		argSeriesDescription, err := decodeSeriesDescription(decoded.SeriesDescription)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeSeriesMutationResult(store.UpdateSeries(ctx, argSeriesID, argSeriesTitle, argSeriesDescription)))
	case methodUpdateSeriesState:
		var decoded updateSeriesStateArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode UpdateSeriesState args: %w", err)
		}
		argSeriesID, err := corewire.DecodeTaskSeriesID(decoded.SeriesID)
		if err != nil {
			return nil, err
		}
		argSeriesState, err := decodeSeriesState(decoded.SeriesState)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeSeriesMutationResult(store.UpdateSeriesState(ctx, argSeriesID, argSeriesState)))
	case methodAddTaskToSeries:
		var decoded addTaskToSeriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode AddTaskToSeries args: %w", err)
		}
		argSeriesID, err := corewire.DecodeTaskSeriesID(decoded.SeriesID)
		if err != nil {
			return nil, err
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeSeriesMutationResult(store.AddTaskToSeries(ctx, argSeriesID, argTaskID)))
	case methodRemoveTaskFromSeries:
		var decoded removeTaskFromSeriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode RemoveTaskFromSeries args: %w", err)
		}
		argSeriesID, err := corewire.DecodeTaskSeriesID(decoded.SeriesID)
		if err != nil {
			return nil, err
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeSeriesMutationResult(store.RemoveTaskFromSeries(ctx, argSeriesID, argTaskID)))
	case methodReorderSeries:
		var decoded reorderSeriesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode ReorderSeries args: %w", err)
		}
		argSeriesID, err := corewire.DecodeTaskSeriesID(decoded.SeriesID)
		if err != nil {
			return nil, err
		}
		argTaskIDs, err := decodeTaskIDs(decoded.TaskIDs)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeSeriesMutationResult(store.ReorderSeries(ctx, argSeriesID, argTaskIDs)))
	case methodCreateSeriesComment:
		var decoded createSeriesCommentArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode CreateSeriesComment args: %w", err)
		}
		argSeriesComment, err := decodeSeriesComment(decoded.SeriesComment)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateSeriesCommentResult(store.CreateSeriesComment(ctx, argSeriesComment)))
	case methodListSeriesComments:
		var decoded listSeriesCommentsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode ListSeriesComments args: %w", err)
		}
		argSeriesID, err := corewire.DecodeTaskSeriesID(decoded.SeriesID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListSeriesCommentsResult(store.ListSeriesComments(ctx, argSeriesID)))
	case methodCreateTaskComment:
		var decoded createTaskCommentArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode CreateTaskComment args: %w", err)
		}
		argTaskComment, err := decodeTaskComment(decoded.TaskComment)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateTaskCommentResult(store.CreateTaskComment(ctx, argTaskComment)))
	case methodListTaskComments:
		var decoded listTaskCommentsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode ListTaskComments args: %w", err)
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListTaskCommentsResult(store.ListTaskComments(ctx, argTaskID)))
	case methodCreateReservation:
		var decoded createReservationArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode CreateReservation args: %w", err)
		}
		argReservationID, err := corewire.DecodeTaskReservationID(decoded.ReservationID)
		if err != nil {
			return nil, err
		}
		argCommand, err := decodeReservationCommand(decoded.Command)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateReservationResult(store.CreateReservation(ctx, argReservationID, argCommand)))
	case methodChangeReservationState:
		var decoded changeReservationStateArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode ChangeReservationState args: %w", err)
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		argReservationID, err := corewire.DecodeTaskReservationID(decoded.ReservationID)
		if err != nil {
			return nil, err
		}
		argReservationState, err := decodeReservationState(decoded.ReservationState)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeChangeReservationStateResult(store.ChangeReservationState(ctx, argTaskID, argReservationID, argReservationState)))
	case methodListReservations:
		var decoded listReservationsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode ListReservations args: %w", err)
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListReservationsResult(store.ListReservations(ctx, argTaskID)))
	case methodCheckSubmissionEligibility:
		var decoded checkSubmissionEligibilityArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("task bridge: decode CheckSubmissionEligibility args: %w", err)
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeSubmissionEligibilityResult(store.CheckSubmissionEligibility(ctx, argTaskID, argUserID)))
	default:
		return nil, fmt.Errorf("task bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements task.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) CreateTask(ctx context.Context, argSeriesID core.TaskSeriesID, argTaskID core.TaskID, argCommand task.CreateCommand) task.CreateTaskStoreResult {
	args, err := json.Marshal(createTaskArgs{SeriesID: corewire.EncodeTaskSeriesID(argSeriesID), TaskID: corewire.EncodeTaskID(argTaskID), Command: encodeCreateCommand(argCommand)})
	if err != nil {
		return task.CreateTaskStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateTask, args)
	if err != nil {
		return task.CreateTaskStoreRejected{Reason: guestError(err)}
	}
	var wire taskResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.CreateTaskStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateTaskResult(wire)
	if err != nil {
		return task.CreateTaskStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FindTask(ctx context.Context, argTaskID core.TaskID) task.FindTaskStoreResult {
	args, err := json.Marshal(findTaskArgs{TaskID: corewire.EncodeTaskID(argTaskID)})
	if err != nil {
		return task.FindTaskStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFindTask, args)
	if err != nil {
		return task.FindTaskStoreRejected{Reason: guestError(err)}
	}
	var wire taskResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.FindTaskStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeFindTaskResult(wire)
	if err != nil {
		return task.FindTaskStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ChangeTaskState(ctx context.Context, argTaskID core.TaskID, argState task.State) task.ChangeTaskStateStoreResult {
	args, err := json.Marshal(changeTaskStateArgs{TaskID: corewire.EncodeTaskID(argTaskID), State: encodeState(argState)})
	if err != nil {
		return task.ChangeTaskStateStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodChangeTaskState, args)
	if err != nil {
		return task.ChangeTaskStateStoreRejected{Reason: guestError(err)}
	}
	var wire taskResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.ChangeTaskStateStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeChangeTaskStateResult(wire)
	if err != nil {
		return task.ChangeTaskStateStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListTasks(ctx context.Context, argScope task.ListScope, argFilters task.ListFilters, argPage core.Page) task.ListTasksStoreResult {
	args, err := json.Marshal(listTasksArgs{Scope: encodeListScope(argScope), Filters: encodeListFilters(argFilters), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return task.ListTasksStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListTasks, args)
	if err != nil {
		return task.ListTasksStoreRejected{Reason: guestError(err)}
	}
	var wire listItemsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.ListTasksStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListTasksResult(wire)
	if err != nil {
		return task.ListTasksStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListSeries(ctx context.Context, argUserID core.UserID, argPage core.Page) task.ListSeriesStoreResult {
	args, err := json.Marshal(listSeriesArgs{UserID: corewire.EncodeUserID(argUserID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return task.ListSeriesStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListSeries, args)
	if err != nil {
		return task.ListSeriesStoreRejected{Reason: guestError(err)}
	}
	var wire seriesListResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.ListSeriesStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListSeriesResult(wire)
	if err != nil {
		return task.ListSeriesStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FindSeries(ctx context.Context, argSeriesID core.TaskSeriesID) task.FindSeriesStoreResult {
	args, err := json.Marshal(findSeriesArgs{SeriesID: corewire.EncodeTaskSeriesID(argSeriesID)})
	if err != nil {
		return task.FindSeriesStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFindSeries, args)
	if err != nil {
		return task.FindSeriesStoreRejected{Reason: guestError(err)}
	}
	var wire seriesDetailResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.FindSeriesStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeFindSeriesResult(wire)
	if err != nil {
		return task.FindSeriesStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) CreateSeries(ctx context.Context, argSeries task.Series) task.SeriesMutationStoreResult {
	args, err := json.Marshal(createSeriesArgs{Series: encodeSeries(argSeries)})
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateSeries, args)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	var wire seriesDetailResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeSeriesMutationResult(wire)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) UpdateSeries(ctx context.Context, argSeriesID core.TaskSeriesID, argSeriesTitle task.SeriesTitle, argSeriesDescription task.SeriesDescription) task.SeriesMutationStoreResult {
	args, err := json.Marshal(updateSeriesArgs{SeriesID: corewire.EncodeTaskSeriesID(argSeriesID), SeriesTitle: encodeSeriesTitle(argSeriesTitle), SeriesDescription: encodeSeriesDescription(argSeriesDescription)})
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodUpdateSeries, args)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	var wire seriesDetailResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeSeriesMutationResult(wire)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) UpdateSeriesState(ctx context.Context, argSeriesID core.TaskSeriesID, argSeriesState task.SeriesState) task.SeriesMutationStoreResult {
	args, err := json.Marshal(updateSeriesStateArgs{SeriesID: corewire.EncodeTaskSeriesID(argSeriesID), SeriesState: encodeSeriesState(argSeriesState)})
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodUpdateSeriesState, args)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	var wire seriesDetailResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeSeriesMutationResult(wire)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) AddTaskToSeries(ctx context.Context, argSeriesID core.TaskSeriesID, argTaskID core.TaskID) task.SeriesMutationStoreResult {
	args, err := json.Marshal(addTaskToSeriesArgs{SeriesID: corewire.EncodeTaskSeriesID(argSeriesID), TaskID: corewire.EncodeTaskID(argTaskID)})
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodAddTaskToSeries, args)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	var wire seriesDetailResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeSeriesMutationResult(wire)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RemoveTaskFromSeries(ctx context.Context, argSeriesID core.TaskSeriesID, argTaskID core.TaskID) task.SeriesMutationStoreResult {
	args, err := json.Marshal(removeTaskFromSeriesArgs{SeriesID: corewire.EncodeTaskSeriesID(argSeriesID), TaskID: corewire.EncodeTaskID(argTaskID)})
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRemoveTaskFromSeries, args)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	var wire seriesDetailResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeSeriesMutationResult(wire)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ReorderSeries(ctx context.Context, argSeriesID core.TaskSeriesID, argTaskIDs []core.TaskID) task.SeriesMutationStoreResult {
	args, err := json.Marshal(reorderSeriesArgs{SeriesID: corewire.EncodeTaskSeriesID(argSeriesID), TaskIDs: encodeTaskIDs(argTaskIDs)})
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodReorderSeries, args)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	var wire seriesDetailResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeSeriesMutationResult(wire)
	if err != nil {
		return task.SeriesMutationStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) CreateSeriesComment(ctx context.Context, argSeriesComment task.SeriesComment) task.CreateSeriesCommentStoreResult {
	args, err := json.Marshal(createSeriesCommentArgs{SeriesComment: encodeSeriesComment(argSeriesComment)})
	if err != nil {
		return task.CreateSeriesCommentStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateSeriesComment, args)
	if err != nil {
		return task.CreateSeriesCommentStoreRejected{Reason: guestError(err)}
	}
	var wire seriesCommentResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.CreateSeriesCommentStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateSeriesCommentResult(wire)
	if err != nil {
		return task.CreateSeriesCommentStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListSeriesComments(ctx context.Context, argSeriesID core.TaskSeriesID) task.ListSeriesCommentsStoreResult {
	args, err := json.Marshal(listSeriesCommentsArgs{SeriesID: corewire.EncodeTaskSeriesID(argSeriesID)})
	if err != nil {
		return task.ListSeriesCommentsStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListSeriesComments, args)
	if err != nil {
		return task.ListSeriesCommentsStoreRejected{Reason: guestError(err)}
	}
	var wire seriesCommentsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.ListSeriesCommentsStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListSeriesCommentsResult(wire)
	if err != nil {
		return task.ListSeriesCommentsStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) CreateTaskComment(ctx context.Context, argTaskComment task.TaskComment) task.CreateTaskCommentStoreResult {
	args, err := json.Marshal(createTaskCommentArgs{TaskComment: encodeTaskComment(argTaskComment)})
	if err != nil {
		return task.CreateTaskCommentStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateTaskComment, args)
	if err != nil {
		return task.CreateTaskCommentStoreRejected{Reason: guestError(err)}
	}
	var wire taskCommentResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.CreateTaskCommentStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateTaskCommentResult(wire)
	if err != nil {
		return task.CreateTaskCommentStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListTaskComments(ctx context.Context, argTaskID core.TaskID) task.ListTaskCommentsStoreResult {
	args, err := json.Marshal(listTaskCommentsArgs{TaskID: corewire.EncodeTaskID(argTaskID)})
	if err != nil {
		return task.ListTaskCommentsStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListTaskComments, args)
	if err != nil {
		return task.ListTaskCommentsStoreRejected{Reason: guestError(err)}
	}
	var wire taskCommentsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.ListTaskCommentsStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListTaskCommentsResult(wire)
	if err != nil {
		return task.ListTaskCommentsStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) CreateReservation(ctx context.Context, argReservationID core.TaskReservationID, argCommand task.ReservationCommand) task.CreateReservationStoreResult {
	args, err := json.Marshal(createReservationArgs{ReservationID: corewire.EncodeTaskReservationID(argReservationID), Command: encodeReservationCommand(argCommand)})
	if err != nil {
		return task.CreateReservationStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateReservation, args)
	if err != nil {
		return task.CreateReservationStoreRejected{Reason: guestError(err)}
	}
	var wire reservationResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.CreateReservationStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateReservationResult(wire)
	if err != nil {
		return task.CreateReservationStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ChangeReservationState(ctx context.Context, argTaskID core.TaskID, argReservationID core.TaskReservationID, argReservationState task.ReservationState) task.ChangeReservationStateStoreResult {
	args, err := json.Marshal(changeReservationStateArgs{TaskID: corewire.EncodeTaskID(argTaskID), ReservationID: corewire.EncodeTaskReservationID(argReservationID), ReservationState: encodeReservationState(argReservationState)})
	if err != nil {
		return task.ChangeReservationStateStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodChangeReservationState, args)
	if err != nil {
		return task.ChangeReservationStateStoreRejected{Reason: guestError(err)}
	}
	var wire reservationResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.ChangeReservationStateStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeChangeReservationStateResult(wire)
	if err != nil {
		return task.ChangeReservationStateStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListReservations(ctx context.Context, argTaskID core.TaskID) task.ListReservationsStoreResult {
	args, err := json.Marshal(listReservationsArgs{TaskID: corewire.EncodeTaskID(argTaskID)})
	if err != nil {
		return task.ListReservationsStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListReservations, args)
	if err != nil {
		return task.ListReservationsStoreRejected{Reason: guestError(err)}
	}
	var wire reservationsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.ListReservationsStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListReservationsResult(wire)
	if err != nil {
		return task.ListReservationsStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) CheckSubmissionEligibility(ctx context.Context, argTaskID core.TaskID, argUserID core.UserID) task.SubmissionEligibilityStoreResult {
	args, err := json.Marshal(checkSubmissionEligibilityArgs{TaskID: corewire.EncodeTaskID(argTaskID), UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return task.SubmissionEligibilityRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCheckSubmissionEligibility, args)
	if err != nil {
		return task.SubmissionEligibilityRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return task.SubmissionEligibilityRejected{Reason: guestError(err)}
	}
	result, err := decodeSubmissionEligibilityResult(wire)
	if err != nil {
		return task.SubmissionEligibilityRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "task bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// task.Store and the bridge is not regenerated, this fails to compile.
var _ task.Store = GuestStore{}
