// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package assetsbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/assets"
	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each assets.Store method on the wire.
const (
	methodCreateCollectible            = "assets.CreateCollectible"
	methodListCollectibles             = "assets.ListCollectibles"
	methodListCollectiblesByOwner      = "assets.ListCollectiblesByOwner"
	methodFundCollectibleReward        = "assets.FundCollectibleReward"
	methodRefundCollectibleReward      = "assets.RefundCollectibleReward"
	methodGiftCollectible              = "assets.GiftCollectible"
	methodAwardOrganizationCollectible = "assets.AwardOrganizationCollectible"
	methodTaskHeldCollectibles         = "assets.TaskHeldCollectibles"
)

type createCollectibleArgs struct {
	Collectible collectibleWire `json:"collectible"`
}

type listCollectiblesArgs struct {
	UserID string            `json:"userid"`
	Page   corewire.PageWire `json:"page"`
}

type listCollectiblesByOwnerArgs struct {
	Query  string            `json:"query"`
	Query2 string            `json:"query2"`
	Page   corewire.PageWire `json:"page"`
}

type fundCollectibleRewardArgs struct {
	Command fundCommandWire `json:"command"`
}

type refundCollectibleRewardArgs struct {
	Command refundCommandWire `json:"command"`
}

type giftCollectibleArgs struct {
	Command giftCommandWire `json:"command"`
}

type awardOrganizationCollectibleArgs struct {
	Command awardCommandWire `json:"command"`
}

type taskHeldCollectiblesArgs struct {
	TaskID string `json:"taskid"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store assets.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreateCollectible:
		var decoded createCollectibleArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("assets bridge: decode CreateCollectible args: %w", err)
		}
		argCollectible, err := decodeCollectible(decoded.Collectible)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateResult(store.CreateCollectible(ctx, argCollectible)))
	case methodListCollectibles:
		var decoded listCollectiblesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("assets bridge: decode ListCollectibles args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.ListCollectibles(ctx, argUserID, argPage)))
	case methodListCollectiblesByOwner:
		var decoded listCollectiblesByOwnerArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("assets bridge: decode ListCollectiblesByOwner args: %w", err)
		}
		argQuery, err := corewire.DecodeString(decoded.Query)
		if err != nil {
			return nil, err
		}
		argQuery2, err := corewire.DecodeString(decoded.Query2)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.ListCollectiblesByOwner(ctx, argQuery, argQuery2, argPage)))
	case methodFundCollectibleReward:
		var decoded fundCollectibleRewardArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("assets bridge: decode FundCollectibleReward args: %w", err)
		}
		argCommand, err := decodeFundCommand(decoded.Command)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeFundRewardResult(store.FundCollectibleReward(ctx, argCommand)))
	case methodRefundCollectibleReward:
		var decoded refundCollectibleRewardArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("assets bridge: decode RefundCollectibleReward args: %w", err)
		}
		argCommand, err := decodeRefundCommand(decoded.Command)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRefundRewardResult(store.RefundCollectibleReward(ctx, argCommand)))
	case methodGiftCollectible:
		var decoded giftCollectibleArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("assets bridge: decode GiftCollectible args: %w", err)
		}
		argCommand, err := decodeGiftCommand(decoded.Command)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeGiftResult(store.GiftCollectible(ctx, argCommand)))
	case methodAwardOrganizationCollectible:
		var decoded awardOrganizationCollectibleArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("assets bridge: decode AwardOrganizationCollectible args: %w", err)
		}
		argCommand, err := decodeAwardCommand(decoded.Command)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeGiftResult(store.AwardOrganizationCollectible(ctx, argCommand)))
	case methodTaskHeldCollectibles:
		var decoded taskHeldCollectiblesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("assets bridge: decode TaskHeldCollectibles args: %w", err)
		}
		argTaskID, err := corewire.DecodeTaskID(decoded.TaskID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeTaskHeldResult(store.TaskHeldCollectibles(ctx, argTaskID)))
	default:
		return nil, fmt.Errorf("assets bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements assets.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) CreateCollectible(ctx context.Context, argCollectible assets.Collectible) assets.CreateStoreResult {
	args, err := json.Marshal(createCollectibleArgs{Collectible: encodeCollectible(argCollectible)})
	if err != nil {
		return assets.CreateStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateCollectible, args)
	if err != nil {
		return assets.CreateStoreRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return assets.CreateStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateResult(wire)
	if err != nil {
		return assets.CreateStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListCollectibles(ctx context.Context, argUserID core.UserID, argPage core.Page) assets.ListStoreResult {
	args, err := json.Marshal(listCollectiblesArgs{UserID: corewire.EncodeUserID(argUserID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return assets.ListStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListCollectibles, args)
	if err != nil {
		return assets.ListStoreRejected{Reason: guestError(err)}
	}
	var wire collectiblesResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return assets.ListStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return assets.ListStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListCollectiblesByOwner(ctx context.Context, argQuery string, argQuery2 string, argPage core.Page) assets.ListStoreResult {
	args, err := json.Marshal(listCollectiblesByOwnerArgs{Query: corewire.EncodeString(argQuery), Query2: corewire.EncodeString(argQuery2), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return assets.ListStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListCollectiblesByOwner, args)
	if err != nil {
		return assets.ListStoreRejected{Reason: guestError(err)}
	}
	var wire collectiblesResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return assets.ListStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return assets.ListStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FundCollectibleReward(ctx context.Context, argCommand assets.FundRewardStoreCommand) assets.FundRewardResult {
	args, err := json.Marshal(fundCollectibleRewardArgs{Command: encodeFundCommand(argCommand)})
	if err != nil {
		return assets.FundRewardRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFundCollectibleReward, args)
	if err != nil {
		return assets.FundRewardRejected{Reason: guestError(err)}
	}
	var wire collectibleResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return assets.FundRewardRejected{Reason: guestError(err)}
	}
	result, err := decodeFundRewardResult(wire)
	if err != nil {
		return assets.FundRewardRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RefundCollectibleReward(ctx context.Context, argCommand assets.RefundRewardStoreCommand) assets.RefundRewardResult {
	args, err := json.Marshal(refundCollectibleRewardArgs{Command: encodeRefundCommand(argCommand)})
	if err != nil {
		return assets.RefundRewardRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRefundCollectibleReward, args)
	if err != nil {
		return assets.RefundRewardRejected{Reason: guestError(err)}
	}
	var wire collectiblesResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return assets.RefundRewardRejected{Reason: guestError(err)}
	}
	result, err := decodeRefundRewardResult(wire)
	if err != nil {
		return assets.RefundRewardRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) GiftCollectible(ctx context.Context, argCommand assets.GiftStoreCommand) assets.GiftResult {
	args, err := json.Marshal(giftCollectibleArgs{Command: encodeGiftCommand(argCommand)})
	if err != nil {
		return assets.GiftRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodGiftCollectible, args)
	if err != nil {
		return assets.GiftRejected{Reason: guestError(err)}
	}
	var wire collectibleResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return assets.GiftRejected{Reason: guestError(err)}
	}
	result, err := decodeGiftResult(wire)
	if err != nil {
		return assets.GiftRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) AwardOrganizationCollectible(ctx context.Context, argCommand assets.AwardOrganizationCollectibleStoreCommand) assets.GiftResult {
	args, err := json.Marshal(awardOrganizationCollectibleArgs{Command: encodeAwardCommand(argCommand)})
	if err != nil {
		return assets.GiftRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodAwardOrganizationCollectible, args)
	if err != nil {
		return assets.GiftRejected{Reason: guestError(err)}
	}
	var wire collectibleResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return assets.GiftRejected{Reason: guestError(err)}
	}
	result, err := decodeGiftResult(wire)
	if err != nil {
		return assets.GiftRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) TaskHeldCollectibles(ctx context.Context, argTaskID core.TaskID) assets.TaskHeldCollectiblesResult {
	args, err := json.Marshal(taskHeldCollectiblesArgs{TaskID: corewire.EncodeTaskID(argTaskID)})
	if err != nil {
		return assets.TaskHeldCollectiblesRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodTaskHeldCollectibles, args)
	if err != nil {
		return assets.TaskHeldCollectiblesRejected{Reason: guestError(err)}
	}
	var wire taskHeldResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return assets.TaskHeldCollectiblesRejected{Reason: guestError(err)}
	}
	result, err := decodeTaskHeldResult(wire)
	if err != nil {
		return assets.TaskHeldCollectiblesRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "assets bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// assets.Store and the bridge is not regenerated, this fails to compile.
var _ assets.Store = GuestStore{}
