// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package moderationtriagebridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/audit"
	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/http"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each httpserver.ModerationTriageService method on the wire.
const (
	methodRecordOpen = "moderationtriage.RecordOpen"
	methodList       = "moderationtriage.List"
	methodUpdate     = "moderationtriage.Update"
)

type recordOpenArgs struct {
	Event eventWire `json:"event"`
}

type listArgs struct {
	IDs []string `json:"ids"`
}

type updateArgs struct {
	UserID   string `json:"userid"`
	ReportID string `json:"reportid"`
	State    string `json:"state"`
	State2   string `json:"state2"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store httpserver.ModerationTriageService, method string, args []byte) ([]byte, error) {
	switch method {
	case methodRecordOpen:
		var decoded recordOpenArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("moderationtriage bridge: decode RecordOpen args: %w", err)
		}
		argEvent, err := decodeEvent(decoded.Event)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMutationResult(store.RecordOpen(ctx, argEvent)))
	case methodList:
		var decoded listArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("moderationtriage bridge: decode List args: %w", err)
		}
		argIDs, err := decodeAuditEventIDs(decoded.IDs)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.List(ctx, argIDs)))
	case methodUpdate:
		var decoded updateArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("moderationtriage bridge: decode Update args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argReportID, err := corewire.DecodeAuditEventID(decoded.ReportID)
		if err != nil {
			return nil, err
		}
		argState, err := corewire.DecodeString(decoded.State)
		if err != nil {
			return nil, err
		}
		argState2, err := corewire.DecodeString(decoded.State2)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMutationResult(store.Update(ctx, argUserID, argReportID, argState, argState2)))
	default:
		return nil, fmt.Errorf("moderationtriage bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements httpserver.ModerationTriageService by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) RecordOpen(ctx context.Context, argEvent audit.Event) httpserver.ModerationTriageMutationResult {
	args, err := json.Marshal(recordOpenArgs{Event: encodeEvent(argEvent)})
	if err != nil {
		return httpserver.ModerationTriageMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRecordOpen, args)
	if err != nil {
		return httpserver.ModerationTriageMutationRejected{Reason: guestError(err)}
	}
	var wire recordResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.ModerationTriageMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeMutationResult(wire)
	if err != nil {
		return httpserver.ModerationTriageMutationRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) List(ctx context.Context, argIDs []core.AuditEventID) httpserver.ModerationTriageListResult {
	args, err := json.Marshal(listArgs{IDs: encodeAuditEventIDs(argIDs)})
	if err != nil {
		return httpserver.ModerationTriageListRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodList, args)
	if err != nil {
		return httpserver.ModerationTriageListRejected{Reason: guestError(err)}
	}
	var wire recordsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.ModerationTriageListRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return httpserver.ModerationTriageListRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) Update(ctx context.Context, argUserID core.UserID, argReportID core.AuditEventID, argState string, argState2 string) httpserver.ModerationTriageMutationResult {
	args, err := json.Marshal(updateArgs{UserID: corewire.EncodeUserID(argUserID), ReportID: corewire.EncodeAuditEventID(argReportID), State: corewire.EncodeString(argState), State2: corewire.EncodeString(argState2)})
	if err != nil {
		return httpserver.ModerationTriageMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodUpdate, args)
	if err != nil {
		return httpserver.ModerationTriageMutationRejected{Reason: guestError(err)}
	}
	var wire recordResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.ModerationTriageMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeMutationResult(wire)
	if err != nil {
		return httpserver.ModerationTriageMutationRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "moderationtriage bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// httpserver.ModerationTriageService and the bridge is not regenerated, this fails to compile.
var _ httpserver.ModerationTriageService = GuestStore{}
