package contracts

import (
	"fmt"
	"path/filepath"
	"strings"
)

const generatedHeader = "-- Generated by sharecrop generate elm-contracts. Do not edit by hand.\n\n"

type ElmFile struct {
	Path    string
	Content string
}

type ElmFilesResult interface {
	elmFilesResult()
}

type ElmFilesGenerated struct {
	Files []ElmFile
}

type ElmFilesRejected struct {
	Reason string
}

func (ElmFilesGenerated) elmFilesResult() {}

func (ElmFilesRejected) elmFilesResult() {}

func GenerateElmFiles(modules []Module) ElmFilesResult {
	files := make([]ElmFile, 0, len(modules))
	for _, module := range modules {
		fileResult := generateElmFile(module)
		fileGenerated, matched := fileResult.(ElmFileGenerated)
		if !matched {
			rejected := fileResult.(ElmFileRejected)
			return ElmFilesRejected{Reason: rejected.Reason}
		}
		files = append(files, fileGenerated.File)
	}
	return ElmFilesGenerated{Files: files}
}

type ElmFileResult interface {
	elmFileResult()
}

type ElmFileGenerated struct {
	File ElmFile
}

type ElmFileRejected struct {
	Reason string
}

func (ElmFileGenerated) elmFileResult() {}

func (ElmFileRejected) elmFileResult() {}

func generateElmFile(module Module) ElmFileResult {
	var builder strings.Builder
	builder.WriteString(generatedHeader)
	builder.WriteString("module ")
	builder.WriteString(module.Name.String())
	builder.WriteString(" exposing (..)\n\n")
	builder.WriteString("import Json.Decode as Decode exposing (Decoder)\n")
	builder.WriteString("import Json.Encode as Encode\n\n")

	for index, definition := range module.Definitions {
		if index > 0 {
			builder.WriteString("\n")
		}
		writeDefinition(&builder, definition)
	}

	return ElmFileGenerated{
		File: ElmFile{
			Path:    modulePath(module.Name),
			Content: builder.String(),
		},
	}
}

func writeDefinition(builder *strings.Builder, definition Definition) {
	switch typed := definition.(type) {
	case Alias:
		writeAlias(builder, typed)
	case Enum:
		writeEnum(builder, typed)
	case Product:
		writeProduct(builder, typed)
	}
}

func writeAlias(builder *strings.Builder, definition Alias) {
	builder.WriteString("type alias ")
	builder.WriteString(definition.Name.String())
	builder.WriteString(" =\n    ")
	builder.WriteString(typeRef(definition.Type))
	builder.WriteString("\n\n")
	writeDecoder(builder, definition.Name, definition.Type)
	writeEncoder(builder, definition.Name, definition.Type)
}

func writeEnum(builder *strings.Builder, definition Enum) {
	builder.WriteString("type ")
	builder.WriteString(definition.Name.String())
	builder.WriteString("\n")
	for index, variant := range definition.Variants {
		if index == 0 {
			builder.WriteString("    = ")
		} else {
			builder.WriteString("    | ")
		}
		builder.WriteString(variant.Name.String())
		builder.WriteString("\n")
	}
	builder.WriteString("\n")
	writeEnumDecoder(builder, definition)
	writeEnumEncoder(builder, definition)
}

func writeProduct(builder *strings.Builder, definition Product) {
	builder.WriteString("type alias ")
	builder.WriteString(definition.Name.String())
	builder.WriteString(" =\n    { ")
	for index, field := range definition.Fields {
		if index > 0 {
			builder.WriteString("\n    , ")
		}
		builder.WriteString(field.Name.String())
		builder.WriteString(" : ")
		builder.WriteString(typeRef(field.Type))
	}
	builder.WriteString("\n    }\n\n")
	writeProductDecoder(builder, definition)
	writeProductEncoder(builder, definition)
}

func writeDecoder(builder *strings.Builder, name ElmTypeName, ref TypeRef) {
	decoderName := lowerFirst(name.String()) + "Decoder"
	builder.WriteString(decoderName)
	builder.WriteString(" : Decoder ")
	builder.WriteString(name.String())
	builder.WriteString("\n")
	builder.WriteString(decoderName)
	builder.WriteString(" =\n    ")
	builder.WriteString(decoderRef(ref))
	builder.WriteString("\n\n")
}

func writeEncoder(builder *strings.Builder, name ElmTypeName, ref TypeRef) {
	encoderName := lowerFirst(name.String()) + "Encoder"
	valueName := lowerFirst(name.String())
	builder.WriteString(encoderName)
	builder.WriteString(" : ")
	builder.WriteString(name.String())
	builder.WriteString(" -> Encode.Value\n")
	builder.WriteString(encoderName)
	builder.WriteString(" ")
	builder.WriteString(valueName)
	builder.WriteString(" =\n    ")
	builder.WriteString(encoderRef(ref, valueName))
	builder.WriteString("\n")
}

func writeEnumDecoder(builder *strings.Builder, definition Enum) {
	decoderName := lowerFirst(definition.Name.String()) + "Decoder"
	builder.WriteString(decoderName)
	builder.WriteString(" : Decoder ")
	builder.WriteString(definition.Name.String())
	builder.WriteString("\n")
	builder.WriteString(decoderName)
	builder.WriteString(" =\n")
	builder.WriteString("    Decode.string\n")
	builder.WriteString("        |> Decode.andThen\n")
	builder.WriteString("            (\\value ->\n")
	builder.WriteString("                case value of\n")
	for _, variant := range definition.Variants {
		builder.WriteString("                    \"")
		builder.WriteString(variant.Tag)
		builder.WriteString("\" ->\n")
		builder.WriteString("                        Decode.succeed ")
		builder.WriteString(variant.Name.String())
		builder.WriteString("\n\n")
	}
	builder.WriteString("                    _ ->\n")
	builder.WriteString("                        Decode.fail \"invalid ")
	builder.WriteString(definition.Name.String())
	builder.WriteString("\"\n")
	builder.WriteString("            )\n\n")
}

func writeEnumEncoder(builder *strings.Builder, definition Enum) {
	encoderName := lowerFirst(definition.Name.String()) + "Encoder"
	valueName := lowerFirst(definition.Name.String())
	builder.WriteString(encoderName)
	builder.WriteString(" : ")
	builder.WriteString(definition.Name.String())
	builder.WriteString(" -> Encode.Value\n")
	builder.WriteString(encoderName)
	builder.WriteString(" ")
	builder.WriteString(valueName)
	builder.WriteString(" =\n")
	builder.WriteString("    case ")
	builder.WriteString(valueName)
	builder.WriteString(" of\n")
	for _, variant := range definition.Variants {
		builder.WriteString("        ")
		builder.WriteString(variant.Name.String())
		builder.WriteString(" ->\n")
		builder.WriteString("            Encode.string \"")
		builder.WriteString(variant.Tag)
		builder.WriteString("\"\n\n")
	}
}

func writeProductDecoder(builder *strings.Builder, definition Product) {
	decoderName := lowerFirst(definition.Name.String()) + "Decoder"
	builder.WriteString(decoderName)
	builder.WriteString(" : Decoder ")
	builder.WriteString(definition.Name.String())
	builder.WriteString("\n")
	builder.WriteString(decoderName)
	builder.WriteString(" =\n")
	if len(definition.Fields) <= 8 {
		writeProductDecoderMap(builder, productDecoderMap(len(definition.Fields)), definition.Name.String(), definition.Fields, "    ")
	} else {
		writeChunkedProductDecoder(builder, definition)
	}
	builder.WriteString("\n")
}

func writeProductDecoderMap(builder *strings.Builder, mapFunction string, constructor string, fields []Field, indent string) {
	builder.WriteString(indent)
	builder.WriteString(mapFunction)
	builder.WriteString(" ")
	builder.WriteString(constructor)
	builder.WriteString("\n")
	for _, field := range fields {
		builder.WriteString(indent)
		builder.WriteString("    ")
		writeFieldDecoder(builder, field)
		builder.WriteString("\n")
	}
}

func writeChunkedProductDecoder(builder *strings.Builder, definition Product) {
	chunkSize := 8
	firstChunk := definition.Fields[:chunkSize]
	writeProductDecoderMap(builder, "Decode.map8", definition.Name.String(), firstChunk, "    ")
	for start := chunkSize; start < len(definition.Fields); start += chunkSize {
		end := start + chunkSize
		if end > len(definition.Fields) {
			end = len(definition.Fields)
		}
		chunk := definition.Fields[start:end]
		builder.WriteString("        |> Decode.andThen\n")
		builder.WriteString("            (\\finish ->\n")
		writeProductDecoderMap(builder, productDecoderMap(len(chunk)), "finish", chunk, "                ")
		builder.WriteString("            )\n")
	}
}

func writeFieldDecoder(builder *strings.Builder, field Field) {
	builder.WriteString("(Decode.field \"")
	builder.WriteString(field.JSONName.String())
	builder.WriteString("\" ")
	builder.WriteString(decoderRef(field.Type))
	builder.WriteString(")")
}

func writeProductEncoder(builder *strings.Builder, definition Product) {
	encoderName := lowerFirst(definition.Name.String()) + "Encoder"
	valueName := lowerFirst(definition.Name.String())
	builder.WriteString(encoderName)
	builder.WriteString(" : ")
	builder.WriteString(definition.Name.String())
	builder.WriteString(" -> Encode.Value\n")
	builder.WriteString(encoderName)
	builder.WriteString(" ")
	builder.WriteString(valueName)
	builder.WriteString(" =\n")
	builder.WriteString("    Encode.object\n")
	builder.WriteString("        [ ")
	for index, field := range definition.Fields {
		if index > 0 {
			builder.WriteString("\n        , ")
		}
		builder.WriteString("( \"")
		builder.WriteString(field.JSONName.String())
		builder.WriteString("\", ")
		builder.WriteString(encoderRef(field.Type, valueName+"."+field.Name.String()))
		builder.WriteString(" )")
	}
	builder.WriteString("\n        ]\n")
}

// productDecoderMap returns the Elm decoder map function for a record with the
// given field count. Elm exposes Decode.map for a single field and
// Decode.mapN for two through eight fields.
func productDecoderMap(fields int) string {
	if fields == 1 {
		return "Decode.map"
	}
	return "Decode.map" + fmt.Sprintf("%d", fields)
}

func typeRef(ref TypeRef) string {
	switch typed := ref.(type) {
	case StringRef:
		return "String"
	case IntRef:
		return "Int"
	case NamedRef:
		return typed.Name.String()
	case ListRef:
		return "List " + typeRef(typed.Element)
	default:
		panic("unknown contract type reference")
	}
}

func decoderRef(ref TypeRef) string {
	switch typed := ref.(type) {
	case StringRef:
		return "Decode.string"
	case IntRef:
		return "Decode.int"
	case NamedRef:
		return lowerFirst(typed.Name.String()) + "Decoder"
	case ListRef:
		return "(Decode.list " + decoderRef(typed.Element) + ")"
	default:
		panic("unknown contract type reference")
	}
}

func encoderRef(ref TypeRef, value string) string {
	switch typed := ref.(type) {
	case StringRef:
		return "Encode.string " + value
	case IntRef:
		return "Encode.int " + value
	case NamedRef:
		return lowerFirst(typed.Name.String()) + "Encoder " + value
	case ListRef:
		return "Encode.list " + encoderFunction(typed.Element) + " " + value
	default:
		panic("unknown contract type reference")
	}
}

func encoderFunction(ref TypeRef) string {
	switch typed := ref.(type) {
	case StringRef:
		return "Encode.string"
	case IntRef:
		return "Encode.int"
	case NamedRef:
		return lowerFirst(typed.Name.String()) + "Encoder"
	case ListRef:
		return "(Encode.list " + encoderFunction(typed.Element) + ")"
	default:
		panic("unknown contract type reference")
	}
}

func modulePath(name ModuleName) string {
	parts := strings.Split(name.String(), ".")
	return filepath.Join(append([]string{"web", "elm", "src"}, parts...)...) + ".elm"
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}
