// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package privacybridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/http"
	"github.com/e6qu/sharecrop/internal/submission"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each httpserver.PrivacyService method on the wire.
const (
	methodCreate                     = "privacy.Create"
	methodListForRequester           = "privacy.ListForRequester"
	methodListAll                    = "privacy.ListAll"
	methodResolve                    = "privacy.Resolve"
	methodRecordSensitiveFieldAccess = "privacy.RecordSensitiveFieldAccess"
	methodRunRetention               = "privacy.RunRetention"
)

type createArgs struct {
	UserID string `json:"userid"`
	Text   string `json:"text"`
}

type listForRequesterArgs struct {
	UserID string            `json:"userid"`
	Page   corewire.PageWire `json:"page"`
}

type listAllArgs struct {
	Page corewire.PageWire `json:"page"`
}

type resolveArgs struct {
	Text  string `json:"text"`
	Text2 string `json:"text2"`
}

type recordSensitiveFieldAccessArgs struct {
	UserID     string         `json:"userid"`
	Submission submissionWire `json:"submission"`
}

type runRetentionArgs struct {
	UserID string `json:"userid"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store httpserver.PrivacyService, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreate:
		var decoded createArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("privacy bridge: decode Create args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argText, err := corewire.DecodeString(decoded.Text)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMutationResult(store.Create(ctx, argUserID, argText)))
	case methodListForRequester:
		var decoded listForRequesterArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("privacy bridge: decode ListForRequester args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.ListForRequester(ctx, argUserID, argPage)))
	case methodListAll:
		var decoded listAllArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("privacy bridge: decode ListAll args: %w", err)
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.ListAll(ctx, argPage)))
	case methodResolve:
		var decoded resolveArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("privacy bridge: decode Resolve args: %w", err)
		}
		argText, err := corewire.DecodeString(decoded.Text)
		if err != nil {
			return nil, err
		}
		argText2, err := corewire.DecodeString(decoded.Text2)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMutationResult(store.Resolve(ctx, argText, argText2)))
	case methodRecordSensitiveFieldAccess:
		var decoded recordSensitiveFieldAccessArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("privacy bridge: decode RecordSensitiveFieldAccess args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argSubmission, err := decodeSubmission(decoded.Submission)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMutationResult(store.RecordSensitiveFieldAccess(ctx, argUserID, argSubmission)))
	case methodRunRetention:
		var decoded runRetentionArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("privacy bridge: decode RunRetention args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRetentionResult(store.RunRetention(ctx, argUserID)))
	default:
		return nil, fmt.Errorf("privacy bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements httpserver.PrivacyService by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) Create(ctx context.Context, argUserID core.UserID, argText string) httpserver.PrivacyMutationResult {
	args, err := json.Marshal(createArgs{UserID: corewire.EncodeUserID(argUserID), Text: corewire.EncodeString(argText)})
	if err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreate, args)
	if err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	var wire recordResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeMutationResult(wire)
	if err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListForRequester(ctx context.Context, argUserID core.UserID, argPage core.Page) httpserver.PrivacyListResult {
	args, err := json.Marshal(listForRequesterArgs{UserID: corewire.EncodeUserID(argUserID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return httpserver.PrivacyRequestListRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListForRequester, args)
	if err != nil {
		return httpserver.PrivacyRequestListRejected{Reason: guestError(err)}
	}
	var wire recordsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PrivacyRequestListRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return httpserver.PrivacyRequestListRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListAll(ctx context.Context, argPage core.Page) httpserver.PrivacyListResult {
	args, err := json.Marshal(listAllArgs{Page: corewire.EncodePage(argPage)})
	if err != nil {
		return httpserver.PrivacyRequestListRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListAll, args)
	if err != nil {
		return httpserver.PrivacyRequestListRejected{Reason: guestError(err)}
	}
	var wire recordsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PrivacyRequestListRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return httpserver.PrivacyRequestListRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) Resolve(ctx context.Context, argText string, argText2 string) httpserver.PrivacyMutationResult {
	args, err := json.Marshal(resolveArgs{Text: corewire.EncodeString(argText), Text2: corewire.EncodeString(argText2)})
	if err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodResolve, args)
	if err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	var wire recordResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeMutationResult(wire)
	if err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RecordSensitiveFieldAccess(ctx context.Context, argUserID core.UserID, argSubmission submission.Submission) httpserver.PrivacyMutationResult {
	args, err := json.Marshal(recordSensitiveFieldAccessArgs{UserID: corewire.EncodeUserID(argUserID), Submission: encodeSubmission(argSubmission)})
	if err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRecordSensitiveFieldAccess, args)
	if err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	var wire recordResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeMutationResult(wire)
	if err != nil {
		return httpserver.PrivacyRequestMutationRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RunRetention(ctx context.Context, argUserID core.UserID) httpserver.PrivacyRetentionResult {
	args, err := json.Marshal(runRetentionArgs{UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return httpserver.PrivacyRetentionRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRunRetention, args)
	if err != nil {
		return httpserver.PrivacyRetentionRejected{Reason: guestError(err)}
	}
	var wire retentionResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PrivacyRetentionRejected{Reason: guestError(err)}
	}
	result, err := decodeRetentionResult(wire)
	if err != nil {
		return httpserver.PrivacyRetentionRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "privacy bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// httpserver.PrivacyService and the bridge is not regenerated, this fails to compile.
var _ httpserver.PrivacyService = GuestStore{}
