// Command gen-seed-snapshot generates the browser demo's pre-seeded database
// snapshot. It migrates and seeds a SQLite database exactly as the demo would on
// a fresh boot, then serializes it to site/demo/seed-snapshot.b64. The demo
// loads this snapshot instead of re-running the (bcrypt-heavy) seed, so it boots
// in a fraction of the time. The snapshot is a build artifact, regenerated by
// the demo build (deno task wasm:demo:build) and git-ignored.
package main

import (
	"context"
	"encoding/base64"
	"log"
	"os"

	"github.com/e6qu/sharecrop/internal/auth"
	"github.com/e6qu/sharecrop/internal/db"
	httpserver "github.com/e6qu/sharecrop/internal/http"
	"github.com/e6qu/sharecrop/internal/sqlitex"
	"github.com/e6qu/sharecrop/internal/wasmseed"
)

const outputPath = "site/demo/seed-snapshot.b64"

func main() {
	ctx := context.Background()

	handle, err := sqlitex.Open("file:/gen-seed-snapshot?vfs=memdb&_pragma=foreign_keys(off)")
	if err != nil {
		log.Fatalf("open sqlite: %v", err)
	}
	defer func() { _ = handle.Close() }()

	if err := db.MigrateUpSQLite(ctx, handle, os.DirFS("migrations")); err != nil {
		log.Fatalf("migrate: %v", err)
	}

	secret, matched := auth.NewAccessTokenSecret("seed-snapshot-generator-secret-not-used-at-runtime").(auth.AccessTokenSecretAccepted)
	if !matched {
		log.Fatal("access token secret rejected")
	}

	stores := wasmseed.StoresFromHandle(db.NewSQLite(handle))
	result := wasmseed.Seed(ctx, secret.Value, stores)
	if result.Err != "" {
		log.Fatalf("seed: %s", result.Err)
	}
	if _, ok := stores.PlatformAdmins.Grant(ctx, result.AdminUserID, result.AdminUserID).(httpserver.PlatformAdminSaved); !ok {
		log.Fatal("grant demo admin failed")
	}

	snapshot, err := sqlitex.Snapshot(ctx, handle)
	if err != nil {
		log.Fatalf("snapshot: %v", err)
	}

	encoded := base64.StdEncoding.EncodeToString(snapshot)
	if err := os.WriteFile(outputPath, []byte(encoded), 0o644); err != nil {
		log.Fatalf("write %s: %v", outputPath, err)
	}
	log.Printf("wrote %s (%d snapshot bytes, %d base64 bytes)", outputPath, len(snapshot), len(encoded))
}
