// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package orgbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/auth"
	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/org"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each org.Store method on the wire.
const (
	methodCreateOrganization       = "org.CreateOrganization"
	methodListOrganizationsForUser = "org.ListOrganizationsForUser"
	methodFindMemberRoles          = "org.FindMemberRoles"
	methodListMembers              = "org.ListMembers"
	methodProvisionMember          = "org.ProvisionMember"
	methodDeactivateMember         = "org.DeactivateMember"
	methodUpdateMemberRoles        = "org.UpdateMemberRoles"
	methodCreateOrganizationTeam   = "org.CreateOrganizationTeam"
	methodCreateStandaloneTeam     = "org.CreateStandaloneTeam"
	methodAddTeamMember            = "org.AddTeamMember"
	methodAddTeamMemberByEmail     = "org.AddTeamMemberByEmail"
	methodListOrganizationTeams    = "org.ListOrganizationTeams"
	methodListStandaloneTeams      = "org.ListStandaloneTeams"
	methodFindTeam                 = "org.FindTeam"
	methodListTeamMembers          = "org.ListTeamMembers"
)

type createOrganizationArgs struct {
	OrganizationID   string `json:"organizationid"`
	OrganizationName string `json:"organizationname"`
	UserID           string `json:"userid"`
	MembershipID     string `json:"membershipid"`
}

type listOrganizationsForUserArgs struct {
	UserID string            `json:"userid"`
	Search string            `json:"search"`
	Page   corewire.PageWire `json:"page"`
}

type findMemberRolesArgs struct {
	OrganizationID string `json:"organizationid"`
	UserID         string `json:"userid"`
}

type listMembersArgs struct {
	OrganizationID string            `json:"organizationid"`
	Page           corewire.PageWire `json:"page"`
}

type provisionMemberArgs struct {
	MembershipID   string   `json:"membershipid"`
	OrganizationID string   `json:"organizationid"`
	Email          string   `json:"email"`
	Roles          []string `json:"roles"`
}

type deactivateMemberArgs struct {
	OrganizationID string `json:"organizationid"`
	UserID         string `json:"userid"`
}

type updateMemberRolesArgs struct {
	OrganizationID string   `json:"organizationid"`
	UserID         string   `json:"userid"`
	Roles          []string `json:"roles"`
}

type createOrganizationTeamArgs struct {
	TeamID         string `json:"teamid"`
	OrganizationID string `json:"organizationid"`
	TeamName       string `json:"teamname"`
	UserID         string `json:"userid"`
}

type createStandaloneTeamArgs struct {
	TeamID   string `json:"teamid"`
	UserID   string `json:"userid"`
	TeamName string `json:"teamname"`
}

type addTeamMemberArgs struct {
	TeamID string `json:"teamid"`
	UserID string `json:"userid"`
}

type addTeamMemberByEmailArgs struct {
	TeamID string `json:"teamid"`
	Email  string `json:"email"`
}

type listOrganizationTeamsArgs struct {
	OrganizationID string            `json:"organizationid"`
	UserID         string            `json:"userid"`
	Search         string            `json:"search"`
	Page           corewire.PageWire `json:"page"`
}

type listStandaloneTeamsArgs struct {
	UserID string            `json:"userid"`
	Search string            `json:"search"`
	Page   corewire.PageWire `json:"page"`
}

type findTeamArgs struct {
	TeamID string `json:"teamid"`
}

type listTeamMembersArgs struct {
	TeamID string `json:"teamid"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store org.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreateOrganization:
		var decoded createOrganizationArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode CreateOrganization args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argOrganizationName, err := decodeOrganizationName(decoded.OrganizationName)
		if err != nil {
			return nil, err
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argMembershipID, err := corewire.DecodeOrganizationMembershipID(decoded.MembershipID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateOrganizationResult(store.CreateOrganization(ctx, argOrganizationID, argOrganizationName, argUserID, argMembershipID)))
	case methodListOrganizationsForUser:
		var decoded listOrganizationsForUserArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode ListOrganizationsForUser args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argSearch, err := corewire.DecodeString(decoded.Search)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListOrganizationsResult(store.ListOrganizationsForUser(ctx, argUserID, argSearch, argPage)))
	case methodFindMemberRoles:
		var decoded findMemberRolesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode FindMemberRoles args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMemberRolesResult(store.FindMemberRoles(ctx, argOrganizationID, argUserID)))
	case methodListMembers:
		var decoded listMembersArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode ListMembers args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListMembersResult(store.ListMembers(ctx, argOrganizationID, argPage)))
	case methodProvisionMember:
		var decoded provisionMemberArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode ProvisionMember args: %w", err)
		}
		argMembershipID, err := corewire.DecodeOrganizationMembershipID(decoded.MembershipID)
		if err != nil {
			return nil, err
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argEmail, err := decodeEmail(decoded.Email)
		if err != nil {
			return nil, err
		}
		argRoles, err := decodeRoles(decoded.Roles)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeProvisionMemberResult(store.ProvisionMember(ctx, argMembershipID, argOrganizationID, argEmail, argRoles)))
	case methodDeactivateMember:
		var decoded deactivateMemberArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode DeactivateMember args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeDeactivateMemberResult(store.DeactivateMember(ctx, argOrganizationID, argUserID)))
	case methodUpdateMemberRoles:
		var decoded updateMemberRolesArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode UpdateMemberRoles args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argRoles, err := decodeRoles(decoded.Roles)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeUpdateMemberRolesResult(store.UpdateMemberRoles(ctx, argOrganizationID, argUserID, argRoles)))
	case methodCreateOrganizationTeam:
		var decoded createOrganizationTeamArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode CreateOrganizationTeam args: %w", err)
		}
		argTeamID, err := corewire.DecodeTeamID(decoded.TeamID)
		if err != nil {
			return nil, err
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argTeamName, err := decodeTeamName(decoded.TeamName)
		if err != nil {
			return nil, err
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateTeamResult(store.CreateOrganizationTeam(ctx, argTeamID, argOrganizationID, argTeamName, argUserID)))
	case methodCreateStandaloneTeam:
		var decoded createStandaloneTeamArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode CreateStandaloneTeam args: %w", err)
		}
		argTeamID, err := corewire.DecodeTeamID(decoded.TeamID)
		if err != nil {
			return nil, err
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argTeamName, err := decodeTeamName(decoded.TeamName)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCreateTeamResult(store.CreateStandaloneTeam(ctx, argTeamID, argUserID, argTeamName)))
	case methodAddTeamMember:
		var decoded addTeamMemberArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode AddTeamMember args: %w", err)
		}
		argTeamID, err := corewire.DecodeTeamID(decoded.TeamID)
		if err != nil {
			return nil, err
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeAddTeamMemberResult(store.AddTeamMember(ctx, argTeamID, argUserID)))
	case methodAddTeamMemberByEmail:
		var decoded addTeamMemberByEmailArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode AddTeamMemberByEmail args: %w", err)
		}
		argTeamID, err := corewire.DecodeTeamID(decoded.TeamID)
		if err != nil {
			return nil, err
		}
		argEmail, err := decodeEmail(decoded.Email)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeAddTeamMemberResult(store.AddTeamMemberByEmail(ctx, argTeamID, argEmail)))
	case methodListOrganizationTeams:
		var decoded listOrganizationTeamsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode ListOrganizationTeams args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argSearch, err := corewire.DecodeString(decoded.Search)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeTeamListResult(store.ListOrganizationTeams(ctx, argOrganizationID, argUserID, argSearch, argPage)))
	case methodListStandaloneTeams:
		var decoded listStandaloneTeamsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode ListStandaloneTeams args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argSearch, err := corewire.DecodeString(decoded.Search)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeTeamListResult(store.ListStandaloneTeams(ctx, argUserID, argSearch, argPage)))
	case methodFindTeam:
		var decoded findTeamArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode FindTeam args: %w", err)
		}
		argTeamID, err := corewire.DecodeTeamID(decoded.TeamID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeFindTeamResult(store.FindTeam(ctx, argTeamID)))
	case methodListTeamMembers:
		var decoded listTeamMembersArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("org bridge: decode ListTeamMembers args: %w", err)
		}
		argTeamID, err := corewire.DecodeTeamID(decoded.TeamID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeTeamMembersResult(store.ListTeamMembers(ctx, argTeamID)))
	default:
		return nil, fmt.Errorf("org bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements org.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) CreateOrganization(ctx context.Context, argOrganizationID core.OrganizationID, argOrganizationName org.OrganizationName, argUserID core.UserID, argMembershipID core.OrganizationMembershipID) org.CreateOrganizationStoreResult {
	args, err := json.Marshal(createOrganizationArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), OrganizationName: encodeOrganizationName(argOrganizationName), UserID: corewire.EncodeUserID(argUserID), MembershipID: corewire.EncodeOrganizationMembershipID(argMembershipID)})
	if err != nil {
		return org.CreateOrganizationStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateOrganization, args)
	if err != nil {
		return org.CreateOrganizationStoreRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.CreateOrganizationStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateOrganizationResult(wire)
	if err != nil {
		return org.CreateOrganizationStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListOrganizationsForUser(ctx context.Context, argUserID core.UserID, argSearch string, argPage core.Page) org.ListOrganizationsResult {
	args, err := json.Marshal(listOrganizationsForUserArgs{UserID: corewire.EncodeUserID(argUserID), Search: corewire.EncodeString(argSearch), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return org.ListOrganizationsRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListOrganizationsForUser, args)
	if err != nil {
		return org.ListOrganizationsRejected{Reason: guestError(err)}
	}
	var wire organizationsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.ListOrganizationsRejected{Reason: guestError(err)}
	}
	result, err := decodeListOrganizationsResult(wire)
	if err != nil {
		return org.ListOrganizationsRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FindMemberRoles(ctx context.Context, argOrganizationID core.OrganizationID, argUserID core.UserID) org.MemberRolesResult {
	args, err := json.Marshal(findMemberRolesArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return org.MemberRolesRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFindMemberRoles, args)
	if err != nil {
		return org.MemberRolesRejected{Reason: guestError(err)}
	}
	var wire memberRolesResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.MemberRolesRejected{Reason: guestError(err)}
	}
	result, err := decodeMemberRolesResult(wire)
	if err != nil {
		return org.MemberRolesRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListMembers(ctx context.Context, argOrganizationID core.OrganizationID, argPage core.Page) org.ListMembersResult {
	args, err := json.Marshal(listMembersArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return org.ListMembersRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListMembers, args)
	if err != nil {
		return org.ListMembersRejected{Reason: guestError(err)}
	}
	var wire membersResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.ListMembersRejected{Reason: guestError(err)}
	}
	result, err := decodeListMembersResult(wire)
	if err != nil {
		return org.ListMembersRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ProvisionMember(ctx context.Context, argMembershipID core.OrganizationMembershipID, argOrganizationID core.OrganizationID, argEmail auth.EmailAddress, argRoles []org.Role) org.ProvisionMemberStoreResult {
	args, err := json.Marshal(provisionMemberArgs{MembershipID: corewire.EncodeOrganizationMembershipID(argMembershipID), OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), Email: encodeEmail(argEmail), Roles: encodeRoles(argRoles)})
	if err != nil {
		return org.ProvisionMemberStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodProvisionMember, args)
	if err != nil {
		return org.ProvisionMemberStoreRejected{Reason: guestError(err)}
	}
	var wire memberResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.ProvisionMemberStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeProvisionMemberResult(wire)
	if err != nil {
		return org.ProvisionMemberStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) DeactivateMember(ctx context.Context, argOrganizationID core.OrganizationID, argUserID core.UserID) org.DeactivateMemberStoreResult {
	args, err := json.Marshal(deactivateMemberArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return org.DeactivateMemberStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodDeactivateMember, args)
	if err != nil {
		return org.DeactivateMemberStoreRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.DeactivateMemberStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeDeactivateMemberResult(wire)
	if err != nil {
		return org.DeactivateMemberStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) UpdateMemberRoles(ctx context.Context, argOrganizationID core.OrganizationID, argUserID core.UserID, argRoles []org.Role) org.UpdateMemberRolesStoreResult {
	args, err := json.Marshal(updateMemberRolesArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), UserID: corewire.EncodeUserID(argUserID), Roles: encodeRoles(argRoles)})
	if err != nil {
		return org.UpdateMemberRolesStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodUpdateMemberRoles, args)
	if err != nil {
		return org.UpdateMemberRolesStoreRejected{Reason: guestError(err)}
	}
	var wire memberResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.UpdateMemberRolesStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeUpdateMemberRolesResult(wire)
	if err != nil {
		return org.UpdateMemberRolesStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) CreateOrganizationTeam(ctx context.Context, argTeamID core.TeamID, argOrganizationID core.OrganizationID, argTeamName org.TeamName, argUserID core.UserID) org.CreateTeamStoreResult {
	args, err := json.Marshal(createOrganizationTeamArgs{TeamID: corewire.EncodeTeamID(argTeamID), OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), TeamName: encodeTeamName(argTeamName), UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return org.CreateTeamStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateOrganizationTeam, args)
	if err != nil {
		return org.CreateTeamStoreRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.CreateTeamStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateTeamResult(wire)
	if err != nil {
		return org.CreateTeamStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) CreateStandaloneTeam(ctx context.Context, argTeamID core.TeamID, argUserID core.UserID, argTeamName org.TeamName) org.CreateTeamStoreResult {
	args, err := json.Marshal(createStandaloneTeamArgs{TeamID: corewire.EncodeTeamID(argTeamID), UserID: corewire.EncodeUserID(argUserID), TeamName: encodeTeamName(argTeamName)})
	if err != nil {
		return org.CreateTeamStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateStandaloneTeam, args)
	if err != nil {
		return org.CreateTeamStoreRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.CreateTeamStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeCreateTeamResult(wire)
	if err != nil {
		return org.CreateTeamStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) AddTeamMember(ctx context.Context, argTeamID core.TeamID, argUserID core.UserID) org.AddTeamMemberStoreResult {
	args, err := json.Marshal(addTeamMemberArgs{TeamID: corewire.EncodeTeamID(argTeamID), UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return org.AddTeamMemberStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodAddTeamMember, args)
	if err != nil {
		return org.AddTeamMemberStoreRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.AddTeamMemberStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeAddTeamMemberResult(wire)
	if err != nil {
		return org.AddTeamMemberStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) AddTeamMemberByEmail(ctx context.Context, argTeamID core.TeamID, argEmail auth.EmailAddress) org.AddTeamMemberStoreResult {
	args, err := json.Marshal(addTeamMemberByEmailArgs{TeamID: corewire.EncodeTeamID(argTeamID), Email: encodeEmail(argEmail)})
	if err != nil {
		return org.AddTeamMemberStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodAddTeamMemberByEmail, args)
	if err != nil {
		return org.AddTeamMemberStoreRejected{Reason: guestError(err)}
	}
	var wire acceptedRejectedWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.AddTeamMemberStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeAddTeamMemberResult(wire)
	if err != nil {
		return org.AddTeamMemberStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListOrganizationTeams(ctx context.Context, argOrganizationID core.OrganizationID, argUserID core.UserID, argSearch string, argPage core.Page) org.TeamListResult {
	args, err := json.Marshal(listOrganizationTeamsArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), UserID: corewire.EncodeUserID(argUserID), Search: corewire.EncodeString(argSearch), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return org.TeamListRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListOrganizationTeams, args)
	if err != nil {
		return org.TeamListRejected{Reason: guestError(err)}
	}
	var wire teamsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.TeamListRejected{Reason: guestError(err)}
	}
	result, err := decodeTeamListResult(wire)
	if err != nil {
		return org.TeamListRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListStandaloneTeams(ctx context.Context, argUserID core.UserID, argSearch string, argPage core.Page) org.TeamListResult {
	args, err := json.Marshal(listStandaloneTeamsArgs{UserID: corewire.EncodeUserID(argUserID), Search: corewire.EncodeString(argSearch), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return org.TeamListRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListStandaloneTeams, args)
	if err != nil {
		return org.TeamListRejected{Reason: guestError(err)}
	}
	var wire teamsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.TeamListRejected{Reason: guestError(err)}
	}
	result, err := decodeTeamListResult(wire)
	if err != nil {
		return org.TeamListRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) FindTeam(ctx context.Context, argTeamID core.TeamID) org.FindTeamResult {
	args, err := json.Marshal(findTeamArgs{TeamID: corewire.EncodeTeamID(argTeamID)})
	if err != nil {
		return org.TeamMissing{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodFindTeam, args)
	if err != nil {
		return org.TeamMissing{Reason: guestError(err)}
	}
	var wire findTeamResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.TeamMissing{Reason: guestError(err)}
	}
	result, err := decodeFindTeamResult(wire)
	if err != nil {
		return org.TeamMissing{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListTeamMembers(ctx context.Context, argTeamID core.TeamID) org.TeamMembersResult {
	args, err := json.Marshal(listTeamMembersArgs{TeamID: corewire.EncodeTeamID(argTeamID)})
	if err != nil {
		return org.TeamMembersRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListTeamMembers, args)
	if err != nil {
		return org.TeamMembersRejected{Reason: guestError(err)}
	}
	var wire teamMembersResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return org.TeamMembersRejected{Reason: guestError(err)}
	}
	result, err := decodeTeamMembersResult(wire)
	if err != nil {
		return org.TeamMembersRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "org bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// org.Store and the bridge is not regenerated, this fails to compile.
var _ org.Store = GuestStore{}
