// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package platformadminbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/http"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each httpserver.PlatformAdminService method on the wire.
const (
	methodIsAdmin = "platformadmin.IsAdmin"
	methodList    = "platformadmin.List"
	methodGrant   = "platformadmin.Grant"
	methodRevoke  = "platformadmin.Revoke"
)

type isAdminArgs struct {
	UserID string `json:"userid"`
}

type listArgs struct {
	Page corewire.PageWire `json:"page"`
}

type grantArgs struct {
	UserID  string `json:"userid"`
	UserID2 string `json:"userid2"`
}

type revokeArgs struct {
	UserID string `json:"userid"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store httpserver.PlatformAdminService, method string, args []byte) ([]byte, error) {
	switch method {
	case methodIsAdmin:
		var decoded isAdminArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("platformadmin bridge: decode IsAdmin args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeCheckResult(store.IsAdmin(ctx, argUserID)))
	case methodList:
		var decoded listArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("platformadmin bridge: decode List args: %w", err)
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.List(ctx, argPage)))
	case methodGrant:
		var decoded grantArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("platformadmin bridge: decode Grant args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		argUserID2, err := corewire.DecodeUserID(decoded.UserID2)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMutationResult(store.Grant(ctx, argUserID, argUserID2)))
	case methodRevoke:
		var decoded revokeArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("platformadmin bridge: decode Revoke args: %w", err)
		}
		argUserID, err := corewire.DecodeUserID(decoded.UserID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeMutationResult(store.Revoke(ctx, argUserID)))
	default:
		return nil, fmt.Errorf("platformadmin bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements httpserver.PlatformAdminService by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) IsAdmin(ctx context.Context, argUserID core.UserID) httpserver.PlatformAdminCheckResult {
	args, err := json.Marshal(isAdminArgs{UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return httpserver.PlatformAdminDenied{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodIsAdmin, args)
	if err != nil {
		return httpserver.PlatformAdminDenied{Reason: guestError(err)}
	}
	var wire checkResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PlatformAdminDenied{Reason: guestError(err)}
	}
	result, err := decodeCheckResult(wire)
	if err != nil {
		return httpserver.PlatformAdminDenied{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) List(ctx context.Context, argPage core.Page) httpserver.PlatformAdminListResult {
	args, err := json.Marshal(listArgs{Page: corewire.EncodePage(argPage)})
	if err != nil {
		return httpserver.PlatformAdminListRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodList, args)
	if err != nil {
		return httpserver.PlatformAdminListRejected{Reason: guestError(err)}
	}
	var wire recordsResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PlatformAdminListRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return httpserver.PlatformAdminListRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) Grant(ctx context.Context, argUserID core.UserID, argUserID2 core.UserID) httpserver.PlatformAdminMutationResult {
	args, err := json.Marshal(grantArgs{UserID: corewire.EncodeUserID(argUserID), UserID2: corewire.EncodeUserID(argUserID2)})
	if err != nil {
		return httpserver.PlatformAdminMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodGrant, args)
	if err != nil {
		return httpserver.PlatformAdminMutationRejected{Reason: guestError(err)}
	}
	var wire recordResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PlatformAdminMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeMutationResult(wire)
	if err != nil {
		return httpserver.PlatformAdminMutationRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) Revoke(ctx context.Context, argUserID core.UserID) httpserver.PlatformAdminMutationResult {
	args, err := json.Marshal(revokeArgs{UserID: corewire.EncodeUserID(argUserID)})
	if err != nil {
		return httpserver.PlatformAdminMutationRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRevoke, args)
	if err != nil {
		return httpserver.PlatformAdminMutationRejected{Reason: guestError(err)}
	}
	var wire recordResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return httpserver.PlatformAdminMutationRejected{Reason: guestError(err)}
	}
	result, err := decodeMutationResult(wire)
	if err != nil {
		return httpserver.PlatformAdminMutationRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "platformadmin bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// httpserver.PlatformAdminService and the bridge is not regenerated, this fails to compile.
var _ httpserver.PlatformAdminService = GuestStore{}
