// Code generated by "sharecrop generate wasi-bridge"; DO NOT EDIT.

package orgcredbridge

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/e6qu/sharecrop/internal/core"
	"github.com/e6qu/sharecrop/internal/orgcred"
	"github.com/e6qu/sharecrop/internal/wasibridge/agentwire"
	"github.com/e6qu/sharecrop/internal/wasibridge/corewire"
)

// Method names namespace each orgcred.Store method on the wire.
const (
	methodCreateCredential = "orgcred.CreateCredential"
	methodVerifyCredential = "orgcred.VerifyCredential"
	methodListCredentials  = "orgcred.ListCredentials"
	methodRevokeCredential = "orgcred.RevokeCredential"
)

type createCredentialArgs struct {
	Credential credentialWire `json:"credential"`
	SecretHash string         `json:"secrethash"`
}

type verifyCredentialArgs struct {
	SecretHash string `json:"secrethash"`
}

type listCredentialsArgs struct {
	OrganizationID string            `json:"organizationid"`
	Page           corewire.PageWire `json:"page"`
}

type revokeCredentialArgs struct {
	OrganizationID string `json:"organizationid"`
	ID             string `json:"id"`
}

// Dispatch services one store call against store: decode the arguments, call the
// real method, encode the result. Every branch is exactly that - no business
// logic lives here.
func Dispatch(ctx context.Context, store orgcred.Store, method string, args []byte) ([]byte, error) {
	switch method {
	case methodCreateCredential:
		var decoded createCredentialArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("orgcred bridge: decode CreateCredential args: %w", err)
		}
		argCredential, err := decodeCredential(decoded.Credential)
		if err != nil {
			return nil, err
		}
		argSecretHash, err := decodeSecretHash(decoded.SecretHash)
		if err != nil {
			return nil, err
		}
		return json.Marshal(agentwire.EncodeCreateStoreResult(store.CreateCredential(ctx, argCredential, argSecretHash)))
	case methodVerifyCredential:
		var decoded verifyCredentialArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("orgcred bridge: decode VerifyCredential args: %w", err)
		}
		argSecretHash, err := decodeSecretHash(decoded.SecretHash)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeVerifyResult(store.VerifyCredential(ctx, argSecretHash)))
	case methodListCredentials:
		var decoded listCredentialsArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("orgcred bridge: decode ListCredentials args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argPage, err := corewire.DecodePage(decoded.Page)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeListResult(store.ListCredentials(ctx, argOrganizationID, argPage)))
	case methodRevokeCredential:
		var decoded revokeCredentialArgs
		if err := json.Unmarshal(args, &decoded); err != nil {
			return nil, fmt.Errorf("orgcred bridge: decode RevokeCredential args: %w", err)
		}
		argOrganizationID, err := corewire.DecodeOrganizationID(decoded.OrganizationID)
		if err != nil {
			return nil, err
		}
		argID, err := corewire.DecodeOrgCredentialID(decoded.ID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(encodeRevokeResult(store.RevokeCredential(ctx, argOrganizationID, argID)))
	default:
		return nil, fmt.Errorf("orgcred bridge: unknown method %q", method)
	}
}

// Invoker sends a store call to the host and returns the serialized result. The
// guest supplies rpc.Invoke; a test can supply an in-process stand-in.
type Invoker func(method string, args []byte) ([]byte, error)

// GuestStore implements orgcred.Store by forwarding each call over an Invoker to
// the host, which services it against the real store. Context is not carried
// across the bridge; the host uses its own context for the real call.
type GuestStore struct {
	invoke Invoker
}

// NewGuestStore builds a GuestStore over the given invoker.
func NewGuestStore(invoke Invoker) GuestStore {
	return GuestStore{invoke: invoke}
}

func (g GuestStore) CreateCredential(ctx context.Context, argCredential orgcred.Credential, argSecretHash orgcred.SecretHash) orgcred.CreateStoreResult {
	args, err := json.Marshal(createCredentialArgs{Credential: encodeCredential(argCredential), SecretHash: encodeSecretHash(argSecretHash)})
	if err != nil {
		return orgcred.CreateStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodCreateCredential, args)
	if err != nil {
		return orgcred.CreateStoreRejected{Reason: guestError(err)}
	}
	var wire agentwire.CreateResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return orgcred.CreateStoreRejected{Reason: guestError(err)}
	}
	result, err := agentwire.DecodeCreateStoreResult(wire)
	if err != nil {
		return orgcred.CreateStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) VerifyCredential(ctx context.Context, argSecretHash orgcred.SecretHash) orgcred.VerifyStoreResult {
	args, err := json.Marshal(verifyCredentialArgs{SecretHash: encodeSecretHash(argSecretHash)})
	if err != nil {
		return orgcred.VerifyStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodVerifyCredential, args)
	if err != nil {
		return orgcred.VerifyStoreRejected{Reason: guestError(err)}
	}
	var wire credentialResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return orgcred.VerifyStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeVerifyResult(wire)
	if err != nil {
		return orgcred.VerifyStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) ListCredentials(ctx context.Context, argOrganizationID core.OrganizationID, argPage core.Page) orgcred.ListStoreResult {
	args, err := json.Marshal(listCredentialsArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), Page: corewire.EncodePage(argPage)})
	if err != nil {
		return orgcred.ListStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodListCredentials, args)
	if err != nil {
		return orgcred.ListStoreRejected{Reason: guestError(err)}
	}
	var wire listResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return orgcred.ListStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeListResult(wire)
	if err != nil {
		return orgcred.ListStoreRejected{Reason: guestError(err)}
	}
	return result
}

func (g GuestStore) RevokeCredential(ctx context.Context, argOrganizationID core.OrganizationID, argID core.OrgCredentialID) orgcred.RevokeStoreResult {
	args, err := json.Marshal(revokeCredentialArgs{OrganizationID: corewire.EncodeOrganizationID(argOrganizationID), ID: corewire.EncodeOrgCredentialID(argID)})
	if err != nil {
		return orgcred.RevokeStoreRejected{Reason: guestError(err)}
	}
	raw, err := g.invoke(methodRevokeCredential, args)
	if err != nil {
		return orgcred.RevokeStoreRejected{Reason: guestError(err)}
	}
	var wire credentialResultWire
	if err := json.Unmarshal(raw, &wire); err != nil {
		return orgcred.RevokeStoreRejected{Reason: guestError(err)}
	}
	result, err := decodeRevokeResult(wire)
	if err != nil {
		return orgcred.RevokeStoreRejected{Reason: guestError(err)}
	}
	return result
}

// guestError wraps a transport/serialization failure as a domain rejection so a
// guest-side call always returns a well-formed result.
func guestError(err error) core.DomainError {
	return core.NewDomainError(core.ErrorCodeInvalidState, "orgcred bridge: "+err.Error())
}

// GuestStore must satisfy the real Store interface - if a method is added to
// orgcred.Store and the bridge is not regenerated, this fails to compile.
var _ orgcred.Store = GuestStore{}
